/**
 * 365 doa/wish ringan universal untuk dokter — dirotasi per hari dalam tahun.
 * Semuanya positif, satu kalimat, tanpa atribut agama spesifik supaya
 * cocok untuk semua dokter. Dipanggil oleh halaman home setelah sapaan waktu.
 *
 * Index = (dayOfYear - 1) % DOA_TEMPLATES.length, sehingga loop natural
 * tiap tahun dan tidak ada hari yang kosong.
 */

export const DOA_TEMPLATES: readonly string[] = [
  // —————————————————————————— kondisi prima · 1–40
  "Semoga hari ini Dokter dalam kondisi prima.",
  "Semoga energi Dokter cukup hingga pasien terakhir.",
  "Semoga tubuh Dokter terjaga sehat menemani siapa pun yang datang.",
  "Semoga napas Dokter ringan, langkah Dokter mantap.",
  "Semoga mata Dokter jernih hingga sore tiba.",
  "Semoga suara Dokter tetap lembut walau hari panjang.",
  "Semoga pundak Dokter ringan, hati Dokter tenang.",
  "Semoga tangan Dokter steady saat memeriksa.",
  "Semoga punggung Dokter kuat menopang seluruh hari.",
  "Semoga senyum Dokter alami, tidak terpaksa.",
  "Semoga tidur tadi malam mengisi penuh stamina hari ini.",
  "Semoga sarapan tadi pagi cukup memberi tenaga.",
  "Semoga teh atau kopi pertama Dokter terasa pas.",
  "Semoga jeda makan siang Dokter tidak terganggu.",
  "Semoga air minum cukup hingga jadwal terakhir.",
  "Semoga peregangan kecil Dokter di sela praktik tetap sempat.",
  "Semoga postur Dokter terjaga saat duduk lama.",
  "Semoga leher Dokter tidak kaku selepas hari ini.",
  "Semoga mata Dokter sempat istirahat dari layar.",
  "Semoga telinga Dokter tetap peka mendengar yang halus.",
  "Semoga jantung Dokter berdetak tenang, tidak terburu-buru.",
  "Semoga pencernaan Dokter nyaman seharian.",
  "Semoga kekebalan Dokter terjaga dari pasien-ke-pasien.",
  "Semoga Dokter pulang dalam keadaan sama sehatnya seperti datang.",
  "Semoga otot Dokter ringan walau berdiri lama.",
  "Semoga tangan Dokter hangat saat menyentuh pasien yang takut.",
  "Semoga refleks Dokter tetap tajam walau lelah mulai datang.",
  "Semoga sirkulasi Dokter lancar selama duduk panjang.",
  "Semoga oksigen ruangan praktik segar untuk Dokter.",
  "Semoga sinar matahari pagi sempat menyapa Dokter.",
  "Semoga hidrasi Dokter tidak pernah turun terlalu jauh.",
  "Semoga gula darah Dokter stabil sepanjang sesi.",
  "Semoga tekanan darah Dokter tetap di angka nyaman.",
  "Semoga koordinasi Dokter halus saat tindakan kecil.",
  "Semoga kepala Dokter tidak pening walau jadwal padat.",
  "Semoga sendi Dokter lentur menemani pemeriksaan demi pemeriksaan.",
  "Semoga organ-organ Dokter saling menjaga hari ini.",
  "Semoga sistem saraf Dokter jernih, bebas tegang.",
  "Semoga Dokter merasakan tubuh sendiri sebagai sekutu, bukan beban.",
  "Semoga rasa lelah datang hanya pada saat yang tepat.",

  // —————————————————————————— urusan dimudahkan · 41–80
  "Semoga setiap urusan Dokter hari ini dimudahkan.",
  "Semoga jalan menuju klinik lancar, tidak macet.",
  "Semoga semua peralatan Dokter berfungsi sebagaimana mestinya.",
  "Semoga jadwal hari ini berjalan tanpa kejutan menumpuk.",
  "Semoga komunikasi dengan rekan kerja jelas dan ringan.",
  "Semoga listrik dan internet stabil sepanjang sesi.",
  "Semoga sistem informasi tidak menambah beban hari ini.",
  "Semoga rujukan yang dibutuhkan terhubung dengan cepat.",
  "Semoga obat-obatan yang Dokter resepkan tersedia di apotek pasien.",
  "Semoga administrasi pasien rapi, mudah dibaca.",
  "Semoga catatan medis hari ini tertulis dengan tenang dan lengkap.",
  "Semoga keputusan-keputusan kecil hari ini terasa ringan, bukan menggantung.",
  "Semoga jadwal antar-pasien memberi cukup ruang untuk berpikir.",
  "Semoga tidak ada hambatan teknis yang merampas waktu Dokter.",
  "Semoga setiap percakapan dengan staf berjalan halus.",
  "Semoga setiap berkas yang dicari mudah ditemukan.",
  "Semoga panggilan telepon yang masuk tidak mengganggu konsultasi.",
  "Semoga email penting tidak tenggelam hari ini.",
  "Semoga pesan WhatsApp yang masuk bisa dijawab dengan cukup waktu.",
  "Semoga kewajiban administratif terselesaikan tanpa lembur.",
  "Semoga laporan-laporan terisi otomatis sebagaimana semestinya.",
  "Semoga tarif dan billing transparan, tidak menimbulkan keraguan pasien.",
  "Semoga perangkat dan kabel di meja periksa tetap rapi.",
  "Semoga ruangan praktik bersih dan nyaman seharian.",
  "Semoga aroma ruangan netral, tidak mengganggu siapa pun.",
  "Semoga suhu ruangan praktik pas, tidak panas tidak dingin.",
  "Semoga jadwal pribadi setelah praktik tidak terganggu.",
  "Semoga keluarga di rumah tidak menunggu terlalu lama hari ini.",
  "Semoga perjalanan pulang Dokter aman dan selamat.",
  "Semoga makan malam nanti terasa nikmat.",
  "Semoga setiap tagihan klinik dibayar tepat waktu hari ini.",
  "Semoga setiap janji ulang tertulis dan diingat sistem.",
  "Semoga setiap surat rujukan sampai pada penerimanya.",
  "Semoga setiap hasil pemeriksaan tiba sebelum keputusan harus diambil.",
  "Semoga peralatan habis-pakai tetap tersedia hari ini.",
  "Semoga stok obat di klinik tidak habis di tengah hari.",
  "Semoga pencairan klaim asuransi tidak tertunda.",
  "Semoga rekan kerja yang sakit segera pulih dan kembali.",
  "Semoga setiap kewajiban hari ini selesai sebelum gelap.",
  "Semoga apa pun yang sulit hari ini, ada jalan keluarnya.",

  // —————————————————————————— pasien membaik · 81–120
  "Semoga setiap pasien hari ini pulang lebih lega.",
  "Semoga keluhan setiap pasien menemukan asalnya, lalu reda.",
  "Semoga pasien yang takut menemukan ketenangan di ruang praktik Dokter.",
  "Semoga pasien anak-anak hari ini tidak menangis berlebihan.",
  "Semoga pasien lansia merasa dimuliakan saat datang.",
  "Semoga pasien dengan rasa sakit menemukan jeda hari ini.",
  "Semoga pasien yang cemas mendapat penjelasan yang menenangkan.",
  "Semoga pasien yang bingung pulang membawa kejelasan.",
  "Semoga setiap diagnosis hari ini tepat sasaran.",
  "Semoga setiap terapi hari ini bekerja sebagaimana diharapkan.",
  "Semoga setiap obat yang diresepkan diminum sesuai aturan.",
  "Semoga setiap edukasi Dokter melekat di ingatan pasien.",
  "Semoga keluarga pasien menerima keadaan dengan hati lapang.",
  "Semoga pasien yang harus dirujuk menerima rujukan dengan tenang.",
  "Semoga pasien pasca-tindakan pulih lebih cepat dari perkiraan.",
  "Semoga pasien dengan penyakit kronis merasa didampingi, bukan dihakimi.",
  "Semoga pasien yang baru pertama kali datang merasa nyaman.",
  "Semoga pasien lama merasa konsisten dipedulikan.",
  "Semoga pasien yang harus operasi mendapat keberanian yang cukup.",
  "Semoga pasien yang menunggu hasil tetap bisa beraktivitas tenang.",
  "Semoga tidak ada pasien yang merasa tergesa hari ini.",
  "Semoga tidak ada pasien yang merasa diabaikan hari ini.",
  "Semoga setiap pasien merasa didengar sebelum diobati.",
  "Semoga setiap pasien pulang membawa setidaknya satu kalimat penghibur.",
  "Semoga setiap pasien menemukan harapan di akhir kunjungan.",
  "Semoga pasien yang membayar terasa pantas atas yang diterima.",
  "Semoga pasien gratis-jaminan merasa setara dengan yang membayar.",
  "Semoga pasien dari jauh merasa perjalanannya tidak sia-sia.",
  "Semoga kondisi kritis dideteksi dini hari ini, bukan terlambat.",
  "Semoga emergency yang masuk hari ini tertangani dengan tepat waktu.",
  "Semoga tidak ada efek samping berat dari pengobatan hari ini.",
  "Semoga interaksi obat semua aman karena diperiksa dengan teliti.",
  "Semoga hasil lab pasien hari ini lebih baik dari sebelumnya.",
  "Semoga pasien yang menunggu antrian tetap nyaman.",
  "Semoga pasien yang batal datang punya alasan yang baik.",
  "Semoga pasien post-operatif tidak demam malam ini.",
  "Semoga semua janji pasien hari ini sesuai jadwal.",
  "Semoga komunikasi dengan keluarga pasien penting tersampaikan jelas.",
  "Semoga keputusan klinis Dokter membawa manfaat jangka panjang.",
  "Semoga semua pasien yang Dokter periksa hari ini mengingat Dokter dengan rasa terima kasih.",

  // —————————————————————————— fokus & ketenangan · 121–160
  "Semoga konsentrasi Dokter terjaga dari pagi hingga sore.",
  "Semoga pikiran Dokter tetap jernih di antara banyak keputusan.",
  "Semoga Dokter mampu hadir penuh untuk setiap pasien — satu per satu.",
  "Semoga gangguan-gangguan kecil tidak merusak fokus Dokter.",
  "Semoga ingatan Dokter cepat memanggil yang relevan.",
  "Semoga Dokter mampu mendengar yang tidak dikatakan pasien.",
  "Semoga Dokter mampu melihat yang tersembunyi di balik gejala.",
  "Semoga intuisi klinis Dokter selaras dengan data hari ini.",
  "Semoga Dokter cukup tenang saat ada kasus sulit.",
  "Semoga Dokter cukup berani saat keputusan harus diambil cepat.",
  "Semoga Dokter cukup sabar saat pasien sulit dipahami.",
  "Semoga Dokter mampu membedakan yang penting dari yang mendesak.",
  "Semoga Dokter mampu berkata 'tidak tahu' tanpa kehilangan otoritas.",
  "Semoga Dokter mampu meminta bantuan tanpa rasa malu.",
  "Semoga Dokter mampu memberi waktu cukup untuk berpikir.",
  "Semoga Dokter tidak terburu-buru di luar kebutuhan.",
  "Semoga Dokter terlindungi dari bias yang merugikan keputusan.",
  "Semoga Dokter membaca riwayat pasien dengan teliti.",
  "Semoga Dokter mendengarkan keluhan utama dengan tuntas.",
  "Semoga Dokter melengkapi pemeriksaan tanpa ada yang terlewat.",
  "Semoga Dokter cukup lapang dada menerima koreksi pasien.",
  "Semoga Dokter cukup percaya diri menjelaskan keputusan.",
  "Semoga Dokter cukup rendah hati menerima tidak tahu segalanya.",
  "Semoga ego Dokter tidak menghalangi keputusan terbaik.",
  "Semoga rasa lelah Dokter tidak mempersempit empati.",
  "Semoga Dokter mampu istirahat sejenak di antara pasien.",
  "Semoga Dokter mampu menarik napas dalam saat tegang.",
  "Semoga Dokter mampu menutup hari ini dengan rasa cukup.",
  "Semoga Dokter mampu meninggalkan pekerjaan saat pulang.",
  "Semoga Dokter mampu menjaga jarak dengan kasus sebelum tidur.",
  "Semoga Dokter mampu memisahkan pekerjaan dari identitas diri.",
  "Semoga Dokter mampu menerima bahwa tidak semua pasien bisa disembuhkan.",
  "Semoga Dokter mampu merayakan kemenangan kecil sendiri.",
  "Semoga Dokter tidak menyalahkan diri atas yang di luar kendali.",
  "Semoga Dokter tidak memikul beban yang seharusnya bukan miliknya.",
  "Semoga Dokter mengenali batas, dan menghormatinya.",
  "Semoga Dokter mampu istirahat tanpa rasa bersalah.",
  "Semoga jeda kopi Dokter terasa lebih panjang dari sekadar hitungan menit.",
  "Semoga ada satu momen hari ini di mana Dokter merasa benar-benar hadir.",
  "Semoga ada satu pasien hari ini yang membuat Dokter teringat alasan memilih profesi ini.",

  // —————————————————————————— hikmah & makna · 161–200
  "Semoga setiap kasus hari ini menambah kebijaksanaan Dokter.",
  "Semoga kesalahan kecil hari ini menjadi pelajaran, bukan beban.",
  "Semoga pengalaman bertahun-tahun Dokter tetap relevan dengan hari ini.",
  "Semoga sumber bacaan baru menemukan jalannya ke meja Dokter.",
  "Semoga jurnal yang dibaca minggu ini melekat di praktik nyata.",
  "Semoga setiap diskusi dengan kolega memperluas perspektif.",
  "Semoga setiap second opinion yang diminta atau diberikan saling menguatkan.",
  "Semoga pertemuan ilmiah berikutnya membawa wawasan segar.",
  "Semoga kasus yang aneh hari ini menjadi cerita yang berguna.",
  "Semoga keraguan hari ini melahirkan ketelitian.",
  "Semoga kepercayaan pasien menjadi pengingat akan tanggung jawab.",
  "Semoga rasa terima kasih pasien tidak membuat Dokter berpuas diri.",
  "Semoga kritik pasien menjadi bahan refleksi yang sehat.",
  "Semoga kegagalan kecil di masa lalu menjaga kewaspadaan hari ini.",
  "Semoga keberhasilan masa lalu menjaga rasa percaya diri yang sehat.",
  "Semoga praktik Dokter tetap relevan terhadap pengetahuan terkini.",
  "Semoga praktik Dokter tetap setia pada nilai-nilai awal mengapa memilih kedokteran.",
  "Semoga Dokter terhubung dengan generasi dokter sebelumnya.",
  "Semoga Dokter sempat berbagi pengetahuan dengan generasi berikutnya.",
  "Semoga ada satu insight kecil hari ini yang layak dicatat.",
  "Semoga catatan reflektif Dokter terus berkembang dari tahun ke tahun.",
  "Semoga Dokter melihat profesi ini sebagai amanah, bukan hanya pekerjaan.",
  "Semoga Dokter menemukan keindahan di anatomi yang biasa-biasa saja.",
  "Semoga rasa kagum pada tubuh manusia tidak pernah pudar.",
  "Semoga rasa hormat pada pasien tidak pernah menjadi rutin.",
  "Semoga rasa takut akan kesalahan tetap proporsional, tidak melumpuhkan.",
  "Semoga Dokter sadar pada batas kedokteran, dan menerimanya dengan tenang.",
  "Semoga Dokter sadar pada kemampuan kedokteran, dan menggunakannya dengan penuh hormat.",
  "Semoga ada keseimbangan antara science dan compassion hari ini.",
  "Semoga ada keseimbangan antara protokol dan keunikan setiap pasien.",
  "Semoga Dokter mampu menerima ketidakpastian sebagai bagian dari profesi.",
  "Semoga Dokter mampu mengakui ketidaktahuan sebagai bentuk kejujuran.",
  "Semoga Dokter mampu meminta maaf jika perlu, tanpa kehilangan martabat.",
  "Semoga Dokter mampu melayani kaya dan miskin dengan kualitas yang sama.",
  "Semoga Dokter mampu hadir untuk kasus yang menyebalkan dengan tetap profesional.",
  "Semoga Dokter mampu mempertahankan keterkejutan terhadap penderitaan.",
  "Semoga Dokter mampu menjaga jarak yang sehat dari penderitaan pasien.",
  "Semoga Dokter mampu pulang sebagai manusia, bukan hanya profesi.",
  "Semoga Dokter mengenali wajah orang-orang terdekat hari ini.",
  "Semoga Dokter sempat duduk diam tanpa beban hari ini.",

  // —————————————————————————— relasi & komunikasi · 201–240
  "Semoga komunikasi Dokter hari ini jelas dan tidak ambigu.",
  "Semoga setiap penjelasan Dokter bisa dimengerti orang awam.",
  "Semoga Dokter sabar saat harus menjelaskan ulang.",
  "Semoga Dokter tidak menggunakan istilah yang membingungkan tanpa perlu.",
  "Semoga Dokter mampu memilih kata yang menenangkan, bukan menakutkan.",
  "Semoga Dokter tetap jujur saat berita harus disampaikan.",
  "Semoga Dokter tetap lembut saat berita yang berat harus diberikan.",
  "Semoga Dokter mampu mendengar tanpa langsung menghakimi.",
  "Semoga Dokter mampu mendengar tanpa langsung memberi solusi.",
  "Semoga Dokter mampu memberi ruang pasien untuk bertanya.",
  "Semoga Dokter mampu menjawab pertanyaan 'aneh' tanpa meremehkan.",
  "Semoga setiap pasien merasa pertanyaannya valid.",
  "Semoga setiap keluarga pasien merasa kekhawatirannya didengar.",
  "Semoga interaksi Dokter dengan staf hari ini hangat.",
  "Semoga relasi Dokter dengan apoteker, perawat, dan teknisi penuh saling hormat.",
  "Semoga koordinasi dengan tim multidisiplin hari ini lancar.",
  "Semoga rapat singkat hari ini benar-benar singkat dan produktif.",
  "Semoga konflik kecil di tempat kerja terselesaikan dengan dewasa.",
  "Semoga rekan sejawat Dokter dalam keadaan sehat dan baik hari ini.",
  "Semoga Dokter mampu memberi pujian yang tulus pada rekan kerja.",
  "Semoga Dokter mampu memberi feedback yang membangun, bukan melukai.",
  "Semoga Dokter mampu menerima feedback tanpa merasa terancam.",
  "Semoga setiap percakapan dengan tetap dalam batas profesional yang sehat.",
  "Semoga Dokter mampu menetapkan batas waktu konsultasi tanpa kasar.",
  "Semoga Dokter tidak terbawa emosi pasien yang sulit.",
  "Semoga Dokter tetap empati pada pasien yang membuat frustrasi.",
  "Semoga Dokter tetap profesional pada pasien yang familiar.",
  "Semoga Dokter mampu meminta tolong tanpa merasa lemah.",
  "Semoga Dokter mampu menolong tanpa merasa lelah secara emosional.",
  "Semoga ucapan terima kasih pasien hari ini menyentuh dengan tepat.",
  "Semoga ucapan keluhan pasien hari ini diterima dengan hati lapang.",
  "Semoga setiap kata Dokter membawa kesembuhan, bukan hanya resep.",
  "Semoga setiap diam Dokter penuh perhatian, bukan kekosongan.",
  "Semoga sentuhan Dokter pada pasien terasa profesional dan penuh hormat.",
  "Semoga setiap salam pembuka dan penutup tidak terasa rutin.",
  "Semoga Dokter sempat menanyakan kabar staf hari ini.",
  "Semoga Dokter sempat menyapa orang-orang yang biasanya tidak terlihat.",
  "Semoga Dokter sempat berterima kasih pada satu orang hari ini.",
  "Semoga ada satu percakapan ringan yang membuat hari ini lebih hangat.",
  "Semoga Dokter mampu pulang membawa sedikit cerita baik untuk keluarga.",

  // —————————————————————————— teknologi & sistem · 241–280
  "Semoga sistem RME hari ini mendukung, bukan menghambat.",
  "Semoga login hari ini lancar, password tidak terlupa.",
  "Semoga setiap input data tersimpan dengan benar.",
  "Semoga tidak ada data yang hilang karena masalah teknis.",
  "Semoga koneksi tetap stabil saat data sedang dikirim.",
  "Semoga sistem tidak lemot saat antrian pasien sedang ramai.",
  "Semoga setiap fitur yang Dokter butuhkan ada di tempat yang mudah dicari.",
  "Semoga setiap notifikasi yang muncul memang penting.",
  "Semoga setiap suggestion sistem benar-benar membantu, bukan mengganggu.",
  "Semoga setiap override Dokter dihormati sistem.",
  "Semoga setiap referensi yang ditampilkan sistem terpercaya.",
  "Semoga setiap modul sistem memudahkan pikiran Dokter, bukan menambah beban.",
  "Semoga setiap update teknologi tidak datang di waktu yang salah.",
  "Semoga setiap bug ditemukan sebelum berdampak ke pasien.",
  "Semoga setiap audit log tercatat dengan jujur.",
  "Semoga laporan-laporan otomatis tepat dan tidak perlu dikoreksi manual.",
  "Semoga billing pasien akurat sejak awal.",
  "Semoga sinkronisasi data antar perangkat berjalan tanpa Dokter sadari.",
  "Semoga sistem tetap aman dari upaya akses yang tidak berwenang.",
  "Semoga privasi pasien terjaga, sebagaimana mestinya.",
  "Semoga setiap berkas digital tersimpan dengan rapi dan mudah dicari kembali.",
  "Semoga komunikasi via WhatsApp dengan pasien tidak menumpuk hari ini.",
  "Semoga email penting tidak tertimbun email tidak penting.",
  "Semoga panggilan telepon dari rumah sakit tertangani saat siap.",
  "Semoga sistem rujukan online mempercepat, bukan memperumit.",
  "Semoga teleresep berjalan baik untuk pasien yang membutuhkannya.",
  "Semoga peralatan periksa Dokter dalam kondisi kalibrasi yang benar.",
  "Semoga lampu periksa terang saat dibutuhkan.",
  "Semoga otoskop, stetoskop, dan alat lain berfungsi penuh hari ini.",
  "Semoga printer tidak menjadi sumber kepanikan hari ini.",
  "Semoga password baru tidak diminta hari ini.",
  "Semoga update aplikasi tidak datang di tengah konsultasi.",
  "Semoga koneksi cetak resep ke apotek lancar.",
  "Semoga setiap perangkat di tas Dokter cukup baterai sampai pulang.",
  "Semoga listrik klinik stabil hingga pasien terakhir.",
  "Semoga AC ruang periksa tetap dingin tapi tidak menggigit.",
  "Semoga pencahayaan ruangan nyaman untuk mata.",
  "Semoga akustik ruangan tidak membuat percakapan tertangkap di ruang sebelah.",
  "Semoga ruangan steril tetap steril.",
  "Semoga semua hal kecil teknis bekerja seperti seharusnya, tanpa drama.",

  // —————————————————————————— rasa syukur · 281–320
  "Semoga Dokter sempat bersyukur atas profesi ini hari ini.",
  "Semoga Dokter sempat bersyukur atas tubuh yang masih bisa bekerja.",
  "Semoga Dokter sempat bersyukur atas pikiran yang masih bisa berpikir.",
  "Semoga Dokter sempat bersyukur atas pasien yang datang dengan kepercayaan.",
  "Semoga Dokter sempat bersyukur atas keluarga yang menanti pulang.",
  "Semoga Dokter sempat bersyukur atas guru-guru yang membentuk diri ini.",
  "Semoga Dokter sempat bersyukur atas teman sejawat yang masih bisa diajak diskusi.",
  "Semoga Dokter sempat bersyukur atas tempat berteduh dan bekerja.",
  "Semoga Dokter sempat bersyukur atas makanan yang dimakan hari ini.",
  "Semoga Dokter sempat bersyukur atas air yang mudah didapat.",
  "Semoga Dokter sempat bersyukur atas kesempatan menolong orang lain.",
  "Semoga Dokter sempat bersyukur atas masalah yang masih bisa diselesaikan.",
  "Semoga Dokter sempat bersyukur atas pelajaran dari kasus yang sulit.",
  "Semoga Dokter sempat bersyukur atas waktu istirahat yang singkat tapi cukup.",
  "Semoga Dokter sempat bersyukur atas senyum tulus seseorang hari ini.",
  "Semoga Dokter sempat bersyukur atas alam di luar jendela.",
  "Semoga Dokter sempat bersyukur atas kemampuan membaca, menulis, dan mendengar.",
  "Semoga Dokter sempat bersyukur atas kebebasan memilih cara berpraktik.",
  "Semoga Dokter sempat bersyukur atas ide-ide yang masih datang.",
  "Semoga Dokter sempat bersyukur atas usia yang masih dipinjamkan.",
  "Semoga Dokter sempat bersyukur atas kejernihan pagi ini, apa pun cuacanya.",
  "Semoga Dokter sempat bersyukur atas kesempatan memulai hari baru.",
  "Semoga Dokter sempat bersyukur atas bahasa yang bisa digunakan untuk menyembuhkan.",
  "Semoga Dokter sempat bersyukur atas rasa empati yang masih hidup.",
  "Semoga Dokter sempat bersyukur atas kemampuan menerima perubahan.",
  "Semoga Dokter sempat bersyukur atas kemampuan menerima keterbatasan.",
  "Semoga Dokter sempat bersyukur atas peluang belajar lebih banyak hari ini.",
  "Semoga Dokter sempat bersyukur atas kesehatan keluarga di rumah.",
  "Semoga Dokter sempat bersyukur atas mimpi yang masih bisa diperjuangkan.",
  "Semoga Dokter sempat bersyukur atas hal-hal kecil yang berjalan benar.",
  "Semoga Dokter sempat bersyukur atas kesempatan untuk berbeda dari kemarin.",
  "Semoga Dokter sempat bersyukur atas waktu yang masih dimiliki.",
  "Semoga Dokter sempat bersyukur atas siapa diri Dokter sekarang.",
  "Semoga Dokter sempat bersyukur atas perjalanan yang sudah dilewati.",
  "Semoga Dokter sempat bersyukur atas perjalanan yang masih menanti.",
  "Semoga Dokter sempat bersyukur atas tanggung jawab yang dipercayakan.",
  "Semoga Dokter sempat bersyukur atas tanggapan baik orang sekitar.",
  "Semoga Dokter sempat bersyukur atas rasa cukup, sebagaimana adanya.",
  "Semoga Dokter sempat bersyukur atas hidup yang sederhana namun bermakna.",
  "Semoga Dokter sempat bersyukur atas kedamaian sesaat di tengah kesibukan.",

  // —————————————————————————— harapan & ke depan · 321–365
  "Semoga hari ini menjadi lebih baik dari kemarin.",
  "Semoga praktik Dokter tahun ini lebih bermakna dari tahun lalu.",
  "Semoga setiap usaha kecil hari ini berbuah kebaikan jangka panjang.",
  "Semoga keinginan baik Dokter untuk pasien sampai pada hasilnya.",
  "Semoga harapan Dokter untuk klinik ini terwujud satu per satu.",
  "Semoga rencana belajar Dokter tahun ini terealisasi.",
  "Semoga rencana istirahat Dokter tahun ini tidak ditunda lagi.",
  "Semoga keluarga Dokter tumbuh dalam kasih dan kesehatan.",
  "Semoga relasi Dokter dengan diri sendiri semakin damai.",
  "Semoga relasi Dokter dengan profesi semakin matang.",
  "Semoga setiap mimpi yang masuk akal menjadi kenyataan.",
  "Semoga setiap doa yang baik dijawab dengan baik.",
  "Semoga setiap niat yang lurus dimudahkan.",
  "Semoga setiap rencana yang dipersiapkan terlaksana.",
  "Semoga setiap kesulitan yang datang sebanding dengan kemampuan Dokter.",
  "Semoga setiap rezeki halal sampai dengan barokah.",
  "Semoga setiap nilai yang Dokter pegang terus dijaga.",
  "Semoga setiap teladan yang Dokter berikan tidak tersia-sia.",
  "Semoga ada warisan baik yang Dokter tinggalkan dari hari ini.",
  "Semoga ada satu pasien yang mengingat Dokter sebagai titik balik kesembuhannya.",
  "Semoga ada satu murid yang mengingat Dokter sebagai contoh yang baik.",
  "Semoga ada satu keputusan hari ini yang menyelamatkan satu nyawa.",
  "Semoga ada satu kalimat hari ini yang membangun seseorang.",
  "Semoga ada satu pertemuan hari ini yang menjadi awal sesuatu yang baik.",
  "Semoga ada satu ide hari ini yang layak dilanjutkan besok.",
  "Semoga ada satu jeda hari ini di mana Dokter sungguh-sungguh tenang.",
  "Semoga ada satu momen hari ini di mana Dokter merasa cukup.",
  "Semoga ada satu momen hari ini di mana Dokter merasa bermakna.",
  "Semoga ada satu momen hari ini di mana Dokter merasa dicintai.",
  "Semoga ada satu momen hari ini di mana Dokter mencintai apa yang dilakukan.",
  "Semoga sore nanti Dokter pulang dengan langkah ringan.",
  "Semoga malam nanti Dokter tertidur tanpa beban yang menggantung.",
  "Semoga besok Dokter bangun dengan harapan baru.",
  "Semoga minggu ini Dokter bisa menjaga ritme kerja yang sehat.",
  "Semoga bulan ini Dokter mendapatkan kabar baik yang ditunggu.",
  "Semoga tahun ini Dokter merasakan pertumbuhan yang berarti.",
  "Semoga setiap tahap karier Dokter berjalan tanpa kehilangan jati diri.",
  "Semoga praktik Dokter selalu mendapat tempat di hati masyarakat.",
  "Semoga pesan-pesan kebaikan dari hari ini terus mengalir, sampai jauh.",
  "Semoga apa pun yang baik untuk Dokter, datang tepat pada waktunya.",
  "Semoga apa pun yang tidak baik untuk Dokter, dijauhkan dengan halus.",
  "Semoga energi positif hari ini mengalir ke setiap pasien yang ditemui.",
  "Semoga hari ini menjadi salah satu hari yang Dokter syukuri tahun depan.",
  "Semoga setiap akhir hari menjadi awal yang lebih bijak.",
  "Semoga keberkahan hari ini meluas ke siapa pun yang Dokter sentuh.",
];

/**
 * Day-of-year (1-366) berbasis WIB (Asia/Jakarta), supaya rotasi doa konsisten
 * untuk semua pengguna sepanjang hari, regardless of timezone perangkat.
 */
export function dayOfYearWIB(date: Date = new Date()): number {
  const formatted = new Intl.DateTimeFormat("en-CA", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    timeZone: "Asia/Jakarta",
  }).format(date);
  const [y, m, d] = formatted.split("-").map(Number);
  const startOfYear = Date.UTC(y, 0, 0);
  const today = Date.UTC(y, m - 1, d);
  return Math.floor((today - startOfYear) / 86_400_000);
}

export function doaHariIni(date: Date = new Date()): string {
  const idx = (dayOfYearWIB(date) - 1 + DOA_TEMPLATES.length) % DOA_TEMPLATES.length;
  return DOA_TEMPLATES[idx];
}
