export type PersonaType = 'pimpinan_daerah' | 'dinas' | 'rs_owner' | 'rs_management' | 'rs_marketing' | 'doctor' | 'hotel_manager' | 'spa_manager' | 'resort_manager' | 'travel_agent' | 'youth_leader' | 'karang_taruna_leader' | 'village_head' | 'tourism_manager' | 'national_park_manager' | 'byanmara';

export type DimensionType = 'aset' | 'potensi' | 'pengetahuan' | 'masalah' | 'rough_idea';

export interface Option {
  label: string;
  value: 1 | 2 | 3 | 4 | 5;
}

export interface Question {
  id: string;
  dimension: DimensionType;
  persona: PersonaType;
  text: string;
  options: Option[];
}

export interface PersonaProfile {
  label: string;
  description: string;
  icon: string;
  questions: Question[];
}

export interface DimensionLabels {
  aset: string;
  potensi: string;
  pengetahuan: string;
  masalah: string;
  rough_idea: string;
}

export const dimensionLabels: DimensionLabels = {
  aset: 'Aset',
  potensi: 'Potensi',
  pengetahuan: 'Pengetahuan',
  masalah: 'Masalah',
  rough_idea: 'Rough Idea',
};

export const dimensionScoreWeights: Record<DimensionType, number> = {
  aset: 0.2,
  potensi: 0.25,
  pengetahuan: 0.2,
  masalah: 0.15,
  rough_idea: 0.2,
};

export const recommendationFrameworks = {
  thailand: {
    minScore: 60,
    label: 'Thailand Premium Model',
    description: 'Medical tourism dengan fokus pada fasilitas premium, patient internasional, dan keunggulan biaya',
  },
  cbt: {
    minScore: 40,
    label: 'Community-Based Tourism Model',
    description: 'Wellness dan culinary tourism berbasis komunitas lokal untuk diaspora dan regional neighbors',
  },
  hybrid: {
    minScore: 50,
    label: 'Hybrid Model',
    description: 'Kombinasi medical tourism premium dengan wellness community-based dan partnership regional',
  },
};

const pimpinanDaerahQuestions: Question[] = [
  {
    id: 'pd_aset_1',
    dimension: 'aset',
    persona: 'pimpinan_daerah',
    text: 'Seberapa kuat komitmen APBD Anda untuk health tourism development dalam 3 tahun ke depan?',
    options: [
      { label: 'Belum dipertimbangkan', value: 1 },
      { label: 'Dalam tahap diskusi awal', value: 2 },
      { label: 'Ada alokasi terbatas (<1% kesehatan budget)', value: 3 },
      { label: 'Ada rencana investasi terstruktur', value: 4 },
      { label: 'Health tourism adalah prioritas strategis daerah', value: 5 },
    ],
  },
  {
    id: 'pd_aset_2',
    dimension: 'aset',
    persona: 'pimpinan_daerah',
    text: 'Seberapa siap infrastruktur transportasi dan akomodasi Anda untuk mendukung medical tourism (bandara, jalan, hotel)?',
    options: [
      { label: 'Sangat minim, perlu pembangunan total', value: 1 },
      { label: 'Ada tapi sangat terbatas dan usang', value: 2 },
      { label: 'Memadai untuk kebutuhan lokal, perlu upgrade', value: 3 },
      { label: 'Baik, dengan beberapa peningkatan minor', value: 4 },
      { label: 'Sangat baik, siap diterima pasien internasional', value: 5 },
    ],
  },
  {
    id: 'pd_potensi_1',
    dimension: 'potensi',
    persona: 'pimpinan_daerah',
    text: 'Berapa jumlah RS/klinik spesialistik yang Anda miliki di daerah dengan potensi internasional?',
    options: [
      { label: 'Tidak ada atau <2 fasilitas minimal', value: 1 },
      { label: '2-3 fasilitas dengan beberapa spesialisasi', value: 2 },
      { label: '4-6 fasilitas dengan spesialisasi terstruktur', value: 3 },
      { label: '7-10 fasilitas dengan komplementaritas baik', value: 4 },
      { label: '>10 fasilitas dengan network klinis kuat', value: 5 },
    ],
  },
  {
    id: 'pd_potensi_2',
    dimension: 'potensi',
    persona: 'pimpinan_daerah',
    text: 'Seberapa besar potensi diaspora dan regional neighbors (Malaysia, Thailand, Brunei, Singapore) yang tertarik ke daerah Anda?',
    options: [
      { label: 'Sangat minimal, lokasi kurang strategis', value: 1 },
      { label: 'Ada tapi sangat kecil, jauh dari hub utama', value: 2 },
      { label: 'Moderat, ada beberapa rute potensial', value: 3 },
      { label: 'Signifikan, lokasi strategis regional', value: 4 },
      { label: 'Sangat tinggi, hub kesehatan regional recognized', value: 5 },
    ],
  },
  {
    id: 'pd_pengetahuan_1',
    dimension: 'pengetahuan',
    persona: 'pimpinan_daerah',
    text: 'Seberapa paham Anda dengan model health tourism internasional (Thailand, Malaysia, Singapore, Korea)?',
    options: [
      { label: 'Tidak tahu, ini topik baru', value: 1 },
      { label: 'Sedikit tahu dari berita/rumor', value: 2 },
      { label: 'Pernah dengar tentang komponen dasarnya', value: 3 },
      { label: 'Sudah pelajari, ada gambaran untuk daerah', value: 4 },
      { label: 'Sangat paham, sudah riset mendalam dan adaptasi lokal', value: 5 },
    ],
  },
  {
    id: 'pd_pengetahuan_2',
    dimension: 'pengetahuan',
    persona: 'pimpinan_daerah',
    text: 'Apakah tim Anda memiliki expertise dalam marketing, regulatory compliance, dan patient coordination internasional?',
    options: [
      { label: 'Tidak ada sama sekali', value: 1 },
      { label: 'Minimal, hanya informal networking', value: 2 },
      { label: 'Ada beberapa orang dengan pengalaman parsial', value: 3 },
      { label: 'Ada tim dedicated tapi perlu strengthening', value: 4 },
      { label: 'Sudah expert team dengan track record international', value: 5 },
    ],
  },
  {
    id: 'pd_masalah_1',
    dimension: 'masalah',
    persona: 'pimpinan_daerah',
    text: 'Apa tantangan terbesar dalam positioning daerah Anda di health tourism regional?',
    options: [
      { label: 'Semua aspek masalah (infrastruktur, fasilitas, brand, semua kosong)', value: 1 },
      { label: 'Fasilitas ada tapi brand/marketing sangat lemah', value: 2 },
      { label: 'Infrastruktur dan fasilitas mulai solid tapi regulatory masalah', value: 3 },
      { label: 'Mostly ready, ada 2-3 masalah spesifik teridentifikasi', value: 4 },
      { label: 'Mostly resolved, hanya fine-tuning dan scaling', value: 5 },
    ],
  },
  {
    id: 'pd_masalah_2',
    dimension: 'masalah',
    persona: 'pimpinan_daerah',
    text: 'Seberapa besar risiko kompetisi dari daerah tetangga atau negara regional lain dalam medical tourism?',
    options: [
      { label: 'Risiko sangat tinggi, sudah kalah jauh', value: 1 },
      { label: 'Risiko tinggi, posisi lemah vs kompetitor', value: 2 },
      { label: 'Risiko moderat, posisi setara dengan competitor utama', value: 3 },
      { label: 'Risiko rendah, ada keunggulan kompetitif jelas', value: 4 },
      { label: 'Risiko minimal, unique positioning sudah kuat', value: 5 },
    ],
  },
  {
    id: 'pd_rough_idea_1',
    dimension: 'rough_idea',
    persona: 'pimpinan_daerah',
    text: 'Apakah Anda sudah punya rough vision/roadmap untuk health tourism daerah dalam 5 tahun?',
    options: [
      { label: 'Belum ada sama sekali', value: 1 },
      { label: 'Ada sketsa awal, belum formal', value: 2 },
      { label: 'Ada rencana tertulis tapi masih general', value: 3 },
      { label: 'Ada roadmap structured dengan tahapan jelas', value: 4 },
      { label: 'Ada strategic plan detail dengan metric dan milestone', value: 5 },
    ],
  },
  {
    id: 'pd_rough_idea_2',
    dimension: 'rough_idea',
    persona: 'pimpinan_daerah',
    text: 'Seberapa urgent kebutuhan Anda untuk implementasi health tourism (dalam berapa bulan target launch)?',
    options: [
      { label: 'Tidak urgent, long-term future idea', value: 1 },
      { label: 'Low priority, mungkin 2-3 tahun', value: 2 },
      { label: 'Moderate, target 12-18 bulan', value: 3 },
      { label: 'High priority, target 6-12 bulan', value: 4 },
      { label: 'Urgent, target 0-6 bulan dengan aksi immediate', value: 5 },
    ],
  },
];

const dinasQuestions: Question[] = [
  {
    id: 'din_aset_1',
    dimension: 'aset',
    persona: 'dinas',
    text: 'Seberapa kuat dukungan dari Dinas Kesehatan/Pariwisata untuk health tourism initiative lokal?',
    options: [
      { label: 'Belum ada koordinasi formal', value: 1 },
      { label: 'Ada rapat awal tapi belum actionable', value: 2 },
      { label: 'Ada dukungan bertahap dengan budget minimal', value: 3 },
      { label: 'Ada dukungan kuat dengan alokasi anggaran terstruktur', value: 4 },
      { label: 'Full support dengan integrated strategy kesehatan-pariwisata', value: 5 },
    ],
  },
  {
    id: 'din_aset_2',
    dimension: 'aset',
    persona: 'dinas',
    text: 'Apakah ada data/mapping tentang fasilitas kesehatan, spesialisasi, dan kapasitas di daerah Anda?',
    options: [
      { label: 'Tidak ada, datanya sangat fragmentasi', value: 1 },
      { label: 'Ada tapi incomplete dan usang', value: 2 },
      { label: 'Ada data dasar, perlu update berkala', value: 3 },
      { label: 'Ada database updated, belum full analytics', value: 4 },
      { label: 'Ada complete ecosystem mapping dengan real-time dashboard', value: 5 },
    ],
  },
  {
    id: 'din_potensi_1',
    dimension: 'potensi',
    persona: 'dinas',
    text: 'Berapa banyak fasilititas kesehatan yang sudah memiliki sertifikasi/akreditasi internasional (JCI, ISO)?',
    options: [
      { label: 'Tidak ada', value: 1 },
      { label: '1-2 fasilitas', value: 2 },
      { label: '3-5 fasilitas', value: 3 },
      { label: '6-10 fasilitas', value: 4 },
      { label: '>10 fasilitas dengan beberapa multi-sertifikasi', value: 5 },
    ],
  },
  {
    id: 'din_potensi_2',
    dimension: 'potensi',
    persona: 'dinas',
    text: 'Seberapa besar network dengan dinas pariwisata, hotel, transportasi untuk ecosystem health tourism?',
    options: [
      { label: 'Tidak ada network formal', value: 1 },
      { label: 'Ada network loose, komunikasi irregular', value: 2 },
      { label: 'Ada koordinasi berkala dengan beberapa stakeholder', value: 3 },
      { label: 'Ada working group structured dengan rapat regular', value: 4 },
      { label: 'Ada integrated task force dengan aligned strategy', value: 5 },
    ],
  },
  {
    id: 'din_pengetahuan_1',
    dimension: 'pengetahuan',
    persona: 'dinas',
    text: 'Seberapa familiar Anda dengan regulatory framework health tourism Indonesia (e-dokumen, cross-border visa, liability)?',
    options: [
      { label: 'Tidak familiar, ini area baru', value: 1 },
      { label: 'Sedikit familiar dari komunikasi informal', value: 2 },
      { label: 'Lumayan familiar, ada implementasi dasar', value: 3 },
      { label: 'Sangat familiar, sudah implementasi kompleks', value: 4 },
      { label: 'Expert level, sering jadi narasumber regulasi', value: 5 },
    ],
  },
  {
    id: 'din_pengetahuan_2',
    dimension: 'pengetahuan',
    persona: 'dinas',
    text: 'Apakah ada standardisasi/protocol health tourism di daerah Anda (patient pathway, safety, quality)?',
    options: [
      { label: 'Tidak ada', value: 1 },
      { label: 'Ada draft awal, belum implementasi', value: 2 },
      { label: 'Ada basic protocol, implementasi parsial', value: 3 },
      { label: 'Ada protocol comprehensive, sudah dijalankan', value: 4 },
      { label: 'Ada certified standard dengan audit regular', value: 5 },
    ],
  },
  {
    id: 'din_masalah_1',
    dimension: 'masalah',
    persona: 'dinas',
    text: 'Apa hambatan utama dalam koordinasi antar dinas/stakeholder untuk health tourism?',
    options: [
      { label: 'Koordinasi sangat sulit, semua dinas silos', value: 1 },
      { label: 'Ada hambatan organisasi tapi bisa dinegosiasi', value: 2 },
      { label: 'Ada hambatan minor, mostly bisa diatasi', value: 3 },
      { label: 'Hambatan minimal, koordinasi sudah lumayan', value: 4 },
      { label: 'Koordinasi very smooth, semua dinas aligned', value: 5 },
    ],
  },
  {
    id: 'din_masalah_2',
    dimension: 'masalah',
    persona: 'dinas',
    text: 'Berapa persen dari fasilititas kesehatan yang ready untuk receive foreign patients (bahasa, billing, process)?',
    options: [
      { label: '<5%, rata-rata belum ready', value: 1 },
      { label: '5-15%, beberapa unit mulai adaptasi', value: 2 },
      { label: '15-30%, ada preparation tapi belum full', value: 3 },
      { label: '30-50%, sudah siap tapi masih ada gap', value: 4 },
      { label: '>50%, sudah sistemik dan experienced', value: 5 },
    ],
  },
  {
    id: 'din_rough_idea_1',
    dimension: 'rough_idea',
    persona: 'dinas',
    text: 'Apakah ada action plan untuk meningkatkan readiness health tourism di daerah Anda?',
    options: [
      { label: 'Tidak ada rencana sama sekali', value: 1 },
      { label: 'Ada ide informal, belum formal action', value: 2 },
      { label: 'Ada planning dasar dengan timeline kasaran', value: 3 },
      { label: 'Ada action plan detail dengan accountability', value: 4 },
      { label: 'Ada integrated program dengan budget dan PM dedicated', value: 5 },
    ],
  },
  {
    id: 'din_rough_idea_2',
    dimension: 'rough_idea',
    persona: 'dinas',
    text: 'Seberapa urgent need Anda untuk capacity building (training, workshop, mentoring) dari expert eksternal?',
    options: [
      { label: 'Tidak urgent, masih banyak hal internal dulu', value: 1 },
      { label: 'Low priority, bisa nanti 1-2 tahun', value: 2 },
      { label: 'Moderate, perlu 6-12 bulan ke depan', value: 3 },
      { label: 'High priority, perlu immediate 3-6 bulan', value: 4 },
      { label: 'Very urgent, perlu mulai sekarang/minggu ini', value: 5 },
    ],
  },
];

const rsOwnerQuestions: Question[] = [
  {
    id: 'rs_owner_aset_1',
    dimension: 'aset',
    persona: 'rs_owner',
    text: 'Seberapa kuat financial position RS Anda untuk invest dalam health tourism infrastructure/capability?',
    options: [
      { label: 'Sangat tight, cashflow barely enough untuk operations', value: 1 },
      { label: 'Tight tapi ada small buffer untuk innovation', value: 2 },
      { label: 'Healthy, ada surplus untuk strategic investment', value: 3 },
      { label: 'Strong, bisa invest significant tanpa cash strain', value: 4 },
      { label: 'Very strong, ada aggressive investment capacity', value: 5 },
    ],
  },
  {
    id: 'rs_owner_aset_2',
    dimension: 'aset',
    persona: 'rs_owner',
    text: 'Apakah fasilitas RS Anda sudah memenuhi standard international (buildings, equipment, lab technology)?',
    options: [
      { label: 'Sangat ketinggalan, banyak equipment lama/tidak standar', value: 1 },
      { label: 'Adequate untuk lokal, tapi below international standard', value: 2 },
      { label: 'Mostly standar dengan beberapa area perlu upgrade', value: 3 },
      { label: 'Sudah near-international standard, detail finishing', value: 4 },
      { label: 'Sudah exceed international standard, world-class facility', value: 5 },
    ],
  },
  {
    id: 'rs_owner_potensi_1',
    dimension: 'potensi',
    persona: 'rs_owner',
    text: 'Berapa persen revenue RS dari patient regional/international saat ini?',
    options: [
      { label: '<1%, almost 0 foreign patient', value: 1 },
      { label: '1-5%, minimal foreign presence', value: 2 },
      { label: '5-10%, ada international patient tapi inconsistent', value: 3 },
      { label: '10-20%, sudah signifikan regional/international mix', value: 4 },
      { label: '>20%, substantial international revenue stream', value: 5 },
    ],
  },
  {
    id: 'rs_owner_potensi_2',
    dimension: 'potensi',
    persona: 'rs_owner',
    text: 'Apakah RS Anda punya unique medical expertise/reputation (specific specialist, treatment, research)?',
    options: [
      { label: 'Tidak jelas, general hospital tanpa spesialisasi', value: 1 },
      { label: 'Ada 1-2 spesialisasi lokal tapi tidak recognized luas', value: 2 },
      { label: 'Ada 3-4 spesialisasi baik dengan regional recognition', value: 3 },
      { label: 'Ada 5+ spesialisasi excellent dengan multi-regional brand', value: 4 },
      { label: 'Ada unique expertise dengan international recognition/publications', value: 5 },
    ],
  },
  {
    id: 'rs_owner_pengetahuan_1',
    dimension: 'pengetahuan',
    persona: 'rs_owner',
    text: 'Seberapa paham Anda dengan business model health tourism (margin, patient cycle, marketing cost)?',
    options: [
      { label: 'Tidak paham, belum riset business case', value: 1 },
      { label: 'Sedikit paham, ada general understanding', value: 2 },
      { label: 'Lumayan paham, ada rough financial picture', value: 3 },
      { label: 'Paham baik, sudah analisis scenario pricing/volume', value: 4 },
      { label: 'Very paham, sudah financial model detail dengan ROI clarity', value: 5 },
    ],
  },
  {
    id: 'rs_owner_pengetahuan_2',
    dimension: 'pengetahuan',
    persona: 'rs_owner',
    text: 'Apakah tim RS sudah trained dalam patient communication international (English, soft skill, cultural sensitivity)?',
    options: [
      { label: 'Tidak ada training sama sekali', value: 1 },
      { label: 'Ada basic English classes tapi tidak specific untuk pasien internasional', value: 2 },
      { label: 'Ada training dasar untuk international interaction', value: 3 },
      { label: 'Ada program training structured untuk patient communication', value: 4 },
      { label: 'Ada comprehensive training dengan regular refresher dan cultural coaching', value: 5 },
    ],
  },
  {
    id: 'rs_owner_masalah_1',
    dimension: 'masalah',
    persona: 'rs_owner',
    text: 'Apa risiko terbesar dalam entering health tourism market?',
    options: [
      { label: 'Semua area berisiko (fasilitas, kapital, expertise, market)', value: 1 },
      { label: 'Financial risk sangat tinggi, ROI unclear', value: 2 },
      { label: 'Operational risk moderat, bisa dimanage', value: 3 },
      { label: 'Risk manageable, mostly ada mitigation plan', value: 4 },
      { label: 'Risk minimal, sudah ada experience dan safeguard', value: 5 },
    ],
  },
  {
    id: 'rs_owner_masalah_2',
    dimension: 'masalah',
    persona: 'rs_owner',
    text: 'Seberapa concern Anda tentang complex liability/malpractice claim dari international patient?',
    options: [
      { label: 'Sangat concerned, tidak punya insurance/framework', value: 1 },
      { label: 'Concerned, insurance ada tapi coverage unclear', value: 2 },
      { label: 'Moderately concerned, ada basic insurance tapi gap potential', value: 3 },
      { label: 'Dapat dikelola, ada comprehensive insurance dan legal protocol', value: 4 },
      { label: 'Confident, ada legal team experienced dan insurance coverage full', value: 5 },
    ],
  },
  {
    id: 'rs_owner_rough_idea_1',
    dimension: 'rough_idea',
    persona: 'rs_owner',
    text: 'Apakah Anda sudah punya business plan health tourism untuk RS dalam 3-5 tahun?',
    options: [
      { label: 'Tidak ada planning sama sekali', value: 1 },
      { label: 'Ada ide awal, belum formalized', value: 2 },
      { label: 'Ada draft business plan basic', value: 3 },
      { label: 'Ada business plan detail dengan financial projection', value: 4 },
      { label: 'Ada strategic health tourism plan dengan execution roadmap dan quarterly targets', value: 5 },
    ],
  },
  {
    id: 'rs_owner_rough_idea_2',
    dimension: 'rough_idea',
    persona: 'rs_owner',
    text: 'Berapa target patient internasional yang ingin Anda capai dalam 1-2 tahun?',
    options: [
      { label: 'Belum punya target, exploratory phase', value: 1 },
      { label: 'Target awal <5 pasien/bulan, testing ground', value: 2 },
      { label: 'Target moderate 5-10 pasien/bulan', value: 3 },
      { label: 'Target ambitious 10-20 pasien/bulan', value: 4 },
      { label: 'Target aggressive >20 pasien/bulan dengan growth plan', value: 5 },
    ],
  },
];

const rsManagementQuestions: Question[] = [
  {
    id: 'rs_mgmt_aset_1',
    dimension: 'aset',
    persona: 'rs_management',
    text: 'Seberapa baik sistem operasional RS untuk menangani volume pasien tambahan dari health tourism?',
    options: [
      { label: 'Sangat ketat, capacity sudah full atau overload', value: 1 },
      { label: 'Tight, ada buffer kecil tapi risky tambah volume', value: 2 },
      { label: 'Adequate, bisa handle moderate increase dengan preparation', value: 3 },
      { label: 'Good buffer, bisa akomodasi significant volume addition', value: 4 },
      { label: 'Excellent capacity planning, scalable dan redundant', value: 5 },
    ],
  },
  {
    id: 'rs_mgmt_aset_2',
    dimension: 'aset',
    persona: 'rs_management',
    text: 'Apakah RS memiliki department/unit dedicated untuk patient relations atau international patient services?',
    options: [
      { label: 'Tidak ada, handle dari reception biasa', value: 1 },
      { label: 'Ada orang part-time untuk patient inquiry', value: 2 },
      { label: 'Ada unit kecil dengan 2-3 staff', value: 3 },
      { label: 'Ada department terstruktur dengan 4-6 staff specialized', value: 4 },
      { label: 'Ada full dedicated International Patient Services dengan multi-function team', value: 5 },
    ],
  },
  {
    id: 'rs_mgmt_potensi_1',
    dimension: 'potensi',
    persona: 'rs_management',
    text: 'Berapa persen dari dokter spesialis RS yang interested/willing untuk pasien internasional?',
    options: [
      { label: '<20%, most dokter reluctant atau tidak interested', value: 1 },
      { label: '20-40%, ada yang interested tapi banyak yang kurang komit', value: 2 },
      { label: '40-60%, sudah good majority supportive', value: 3 },
      { label: '60-80%, most dokter interested dan engaged', value: 4 },
      { label: '>80%, overwhelming dokter support dan enthusiasm', value: 5 },
    ],
  },
  {
    id: 'rs_mgmt_potensi_2',
    dimension: 'potensi',
    persona: 'rs_management',
    text: 'Apakah RS sudah punya network/partnership dengan medical tourism facilitator, travel agent, insurance?',
    options: [
      { label: 'Tidak ada network sama sekali', value: 1 },
      { label: 'Ada contact informal, belum formal partnership', value: 2 },
      { label: 'Ada 1-2 partnership dasar', value: 3 },
      { label: 'Ada 3-5 partnership aktif dengan referral established', value: 4 },
      { label: 'Ada robust network dengan 5+ partners strong dan growing', value: 5 },
    ],
  },
  {
    id: 'rs_mgmt_pengetahuan_1',
    dimension: 'pengetahuan',
    persona: 'rs_management',
    text: 'Seberapa familiar management dengan international patient protocol (checkin, billing, discharge, follow-up)?',
    options: [
      { label: 'Tidak familiar, belum ada protocol', value: 1 },
      { label: 'Sedikit familiar dari ad-hoc experience', value: 2 },
      { label: 'Lumayan familiar, ada basic protocol', value: 3 },
      { label: 'Sangat familiar, ada comprehensive protocol documented', value: 4 },
      { label: 'Expert, ada optimized protocol dengan continuous improvement', value: 5 },
    ],
  },
  {
    id: 'rs_mgmt_pengetahuan_2',
    dimension: 'pengetahuan',
    persona: 'rs_management',
    text: 'Apakah ada training program untuk staff tentang hospitality dan cultural difference dalam serving international patient?',
    options: [
      { label: 'Tidak ada training', value: 1 },
      { label: 'Ada ad-hoc training atau informal mentoring', value: 2 },
      { label: 'Ada basic training program untuk new staff', value: 3 },
      { label: 'Ada structured training program dengan regular updates', value: 4 },
      { label: 'Ada comprehensive training dengan cultural coach dan external facilitator', value: 5 },
    ],
  },
  {
    id: 'rs_mgmt_masalah_1',
    dimension: 'masalah',
    persona: 'rs_management',
    text: 'Apa hambatan operasional terbesar dalam melayani international patient?',
    options: [
      { label: 'Banyak hambatan (bahasa, sistem, mindset, efficiency)', value: 1 },
      { label: 'Ada hambatan signifikan dalam beberapa area', value: 2 },
      { label: 'Ada hambatan minor tapi manageable', value: 3 },
      { label: 'Hambatan minimal, mostly operational siap', value: 4 },
      { label: 'Tidak ada hambatan signifikan, semua smooth', value: 5 },
    ],
  },
  {
    id: 'rs_mgmt_masalah_2',
    dimension: 'masalah',
    persona: 'rs_management',
    text: 'Seberapa confident RS dalam managing patient expectation dan satisfaction untuk international client?',
    options: [
      { label: 'Tidak confident, belum ada experience', value: 1 },
      { label: 'Somewhat unconfident, ada gaps dalam service standard', value: 2 },
      { label: 'Moderately confident, ada improvement potential', value: 3 },
      { label: 'Confident, sudah ada track record baik', value: 4 },
      { label: 'Very confident, consistent high satisfaction dari international patient', value: 5 },
    ],
  },
  {
    id: 'rs_mgmt_rough_idea_1',
    dimension: 'rough_idea',
    persona: 'rs_management',
    text: 'Apakah ada operasional plan untuk scale-up international patient services?',
    options: [
      { label: 'Tidak ada plan sama sekali', value: 1 },
      { label: 'Ada rough idea, belum actionable', value: 2 },
      { label: 'Ada basic operational plan', value: 3 },
      { label: 'Ada detailed operational plan dengan timeline', value: 4 },
      { label: 'Ada comprehensive plan dengan budget dan accountable owner', value: 5 },
    ],
  },
  {
    id: 'rs_mgmt_rough_idea_2',
    dimension: 'rough_idea',
    persona: 'rs_management',
    text: 'Seberapa urgent butuh support/mentoring dari expert eksternal untuk health tourism operations?',
    options: [
      { label: 'Tidak urgent, bisa internal dulu', value: 1 },
      { label: 'Low priority, bisa nanti', value: 2 },
      { label: 'Moderate, perlu 6-12 bulan ini', value: 3 },
      { label: 'High priority, perlu 3-6 bulan ini', value: 4 },
      { label: 'Very urgent, perlu dimulai ASAP atau minggu ini', value: 5 },
    ],
  },
];

const rsMarketingQuestions: Question[] = [
  {
    id: 'rs_mkt_aset_1',
    dimension: 'aset',
    persona: 'rs_marketing',
    text: 'Seberapa baik digital marketing presence RS (website, SEO, social media, review platform)?',
    options: [
      { label: 'Sangat minim, almost no digital presence', value: 1 },
      { label: 'Ada basic website tapi outdated, minimal social media', value: 2 },
      { label: 'Ada decent website dan social media, tapi SEO lemah', value: 3 },
      { label: 'Ada good digital presence, mulai muncul di search engine', value: 4 },
      { label: 'Ada strong digital presence dengan consistent engagement dan good SEO ranking', value: 5 },
    ],
  },
  {
    id: 'rs_mkt_aset_2',
    dimension: 'aset',
    persona: 'rs_marketing',
    text: 'Apakah tim marketing RS punya expertise dalam international market/content creation?',
    options: [
      { label: 'Tidak ada team marketing serius, mostly admin', value: 1 },
      { label: 'Ada 1 staff marketing tapi fokus lokal saja', value: 2 },
      { label: 'Ada small team marketing dengan basic international awareness', value: 3 },
      { label: 'Ada dedicated marketing team dengan some international experience', value: 4 },
      { label: 'Ada strong marketing team dengan international campaign experience', value: 5 },
    ],
  },
  {
    id: 'rs_mkt_potensi_1',
    dimension: 'potensi',
    persona: 'rs_marketing',
    text: 'Berapa lead incoming per bulan dari digital atau organic search saat ini?',
    options: [
      { label: '<10 lead/bulan, very minimal', value: 1 },
      { label: '10-50 lead/bulan, ada tapi small volume', value: 2 },
      { label: '50-100 lead/bulan, moderate volume', value: 3 },
      { label: '100-200 lead/bulan, good volume incoming', value: 4 },
      { label: '>200 lead/bulan, strong consistent lead generation', value: 5 },
    ],
  },
  {
    id: 'rs_mkt_potensi_2',
    dimension: 'potensi',
    persona: 'rs_marketing',
    text: 'Apakah ada budget marketing yang bisa dialokasikan untuk health tourism campaign?',
    options: [
      { label: 'Tidak ada budget sama sekali', value: 1 },
      { label: 'Ada tapi sangat minimal (<1% revenue)', value: 2 },
      { label: 'Ada budget limited (1-2% revenue) untuk basic campaign', value: 3 },
      { label: 'Ada budget decent (2-5% revenue) untuk strategic campaign', value: 4 },
      { label: 'Ada substantial budget (>5% revenue) untuk growth aggressive', value: 5 },
    ],
  },
  {
    id: 'rs_mkt_pengetahuan_1',
    dimension: 'pengetahuan',
    persona: 'rs_marketing',
    text: 'Seberapa paham Anda dengan international patient journey (awareness, consideration, decision, advocacy)?',
    options: [
      { label: 'Tidak paham, belum pelajari', value: 1 },
      { label: 'Sedikit paham dari general knowledge', value: 2 },
      { label: 'Lumayan paham, ada basic understanding', value: 3 },
      { label: 'Paham baik, sudah integrated dalam strategy marketing', value: 4 },
      { label: 'Very paham, sudah operationalize dalam campaign dan measurement', value: 5 },
    ],
  },
  {
    id: 'rs_mkt_pengetahuan_2',
    dimension: 'pengetahuan',
    persona: 'rs_marketing',
    text: 'Apakah marketing team sudah familiar dengan international medical tourism marketing best practice?',
    options: [
      { label: 'Tidak familiar, ini area baru sama sekali', value: 1 },
      { label: 'Sedikit familiar dari research atau conference', value: 2 },
      { label: 'Lumayan familiar, ada beberapa best practice diterapkan', value: 3 },
      { label: 'Sangat familiar, sudah implementasi multiple strategy', value: 4 },
      { label: 'Expert level, sering training tim internal atau external', value: 5 },
    ],
  },
  {
    id: 'rs_mkt_masalah_1',
    dimension: 'masalah',
    persona: 'rs_marketing',
    text: 'Apa hambatan terbesar dalam positioning RS untuk health tourism market?',
    options: [
      { label: 'Banyak hambatan (brand weak, no content, no international presence)', value: 1 },
      { label: 'Ada hambatan signifikan dalam beberapa area', value: 2 },
      { label: 'Ada hambatan minor tapi identifiable dan fixable', value: 3 },
      { label: 'Hambatan minimal, mostly positioning strong', value: 4 },
      { label: 'Tidak ada hambatan major, ready untuk market international', value: 5 },
    ],
  },
  {
    id: 'rs_mkt_masalah_2',
    dimension: 'masalah',
    persona: 'rs_marketing',
    text: 'Seberapa competitive environment untuk health tourism di region Anda?',
    options: [
      { label: 'Sangat competitive, banyak player established', value: 1 },
      { label: 'Competitive, ada beberapa pemain kuat', value: 2 },
      { label: 'Moderately competitive, ada opportunities whitespace', value: 3 },
      { label: 'Less competitive, RS bisa differentiate jelas', value: 4 },
      { label: 'Tidak competitive, first-mover advantage clear', value: 5 },
    ],
  },
  {
    id: 'rs_mkt_rough_idea_1',
    dimension: 'rough_idea',
    persona: 'rs_marketing',
    text: 'Apakah sudah ada health tourism marketing campaign plan yang disetujui leadership?',
    options: [
      { label: 'Tidak ada plan sama sekali', value: 1 },
      { label: 'Ada idea informal, belum formal approval', value: 2 },
      { label: 'Ada draft plan, sedang diajukan', value: 3 },
      { label: 'Ada approved campaign plan dengan timeline execution', value: 4 },
      { label: 'Ada comprehensive plan dengan budget allocated dan PM dedicated', value: 5 },
    ],
  },
  {
    id: 'rs_mkt_rough_idea_2',
    dimension: 'rough_idea',
    persona: 'rs_marketing',
    text: 'Seberapa urgent kebutuhan untuk marketing strategy development atau rebranding untuk health tourism?',
    options: [
      { label: 'Tidak urgent, fase exploratory dulu', value: 1 },
      { label: 'Low priority, bisa nanti 1-2 tahun', value: 2 },
      { label: 'Moderate priority, perlu 6-12 bulan ini', value: 3 },
      { label: 'High priority, perlu 3-6 bulan ini', value: 4 },
      { label: 'Very urgent, perlu immediate action atau minggu ini', value: 5 },
    ],
  },
];

const doctorQuestions: Question[] = [
  {
    id: 'doc_aset_1',
    dimension: 'aset',
    persona: 'doctor',
    text: 'Seberapa besar potensi earning dari melayani international patient dibanding pasien lokal?',
    options: [
      { label: 'Sangat kecil, tidak significant', value: 1 },
      { label: 'Kecil, maybe 5-10% additional income', value: 2 },
      { label: 'Moderat, 10-20% additional income potential', value: 3 },
      { label: 'Significant, 20-40% additional income', value: 4 },
      { label: 'Very significant, >40% atau bisa multiple income stream', value: 5 },
    ],
  },
  {
    id: 'doc_aset_2',
    dimension: 'aset',
    persona: 'doctor',
    text: 'Apakah Anda sudah punya experience melayani international/English-speaking patient?',
    options: [
      { label: 'Tidak ada experience sama sekali', value: 1 },
      { label: 'Ada minimal experience, 1-3 international patient', value: 2 },
      { label: 'Ada moderate experience, 4-10 international patient', value: 3 },
      { label: 'Ada good experience, 11-30+ international patient', value: 4 },
      { label: 'Ada extensive experience, >30 international patient treated well', value: 5 },
    ],
  },
  {
    id: 'doc_potensi_1',
    dimension: 'potensi',
    persona: 'doctor',
    text: 'Seberapa kuat expertise/specialization Anda dalam kelompok prosedur yang ada demand internasional?',
    options: [
      { label: 'Tidak jelas, general practitioner', value: 1 },
      { label: 'Specialty ada tapi belum recognized luas', value: 2 },
      { label: 'Specialty jelas dengan reputation lokal baik', value: 3 },
      { label: 'Specialty kuat dengan reputation regional', value: 4 },
      { label: 'Specialty excellence dengan reputation internasional atau unique expertise', value: 5 },
    ],
  },
  {
    id: 'doc_potensi_2',
    dimension: 'potensi',
    persona: 'doctor',
    text: 'Apakah Anda interested untuk develop skill (training, certification, publication) untuk attract international patient?',
    options: [
      { label: 'Tidak interested, fokus pasien lokal saja', value: 1 },
      { label: 'Sedikit interested tapi low priority', value: 2 },
      { label: 'Moderately interested, ada plan development', value: 3 },
      { label: 'Interested, sudah ada some development ongoing', value: 4 },
      { label: 'Very interested, committed untuk continuous skill upgrade', value: 5 },
    ],
  },
  {
    id: 'doc_pengetahuan_1',
    dimension: 'pengetahuan',
    persona: 'doctor',
    text: 'Seberapa fluent English Anda untuk medical consultation dengan international patient?',
    options: [
      { label: 'Tidak fluent, sangat terbatas', value: 1 },
      { label: 'Basic English, dapat communicate tapi slow/translation diperlukan', value: 2 },
      { label: 'Decent English, bisa medical discussion tapi ada accent/vocabulary gap', value: 3 },
      { label: 'Fluent English, bisa consult confident dengan international patient', value: 4 },
      { label: 'Native-level fluency, bisa nuance discussion atau teaching', value: 5 },
    ],
  },
  {
    id: 'doc_pengetahuan_2',
    dimension: 'pengetahuan',
    persona: 'doctor',
    text: 'Apakah Anda pernah training/exposure tentang international patient management (expectation, documentation, ethical)?',
    options: [
      { label: 'Tidak ada training sama sekali', value: 1 },
      { label: 'Ada informal exposure dari experience', value: 2 },
      { label: 'Ada basic training dari workshop atau conference', value: 3 },
      { label: 'Ada substantial training dengan comprehensive coverage', value: 4 },
      { label: 'Ada expert-level training dengan continuing education', value: 5 },
    ],
  },
  {
    id: 'doc_masalah_1',
    dimension: 'masalah',
    persona: 'doctor',
    text: 'Apa concern terbesar Anda dalam melayani international patient?',
    options: [
      { label: 'Banyak concern (liability, communication, expectation, time management)', value: 1 },
      { label: 'Ada concern signifikan dalam beberapa area', value: 2 },
      { label: 'Ada concern minor tapi manageable', value: 3 },
      { label: 'Minimal concern, sudah ada experience', value: 4 },
      { label: 'Tidak ada major concern, confident melayani international patient', value: 5 },
    ],
  },
  {
    id: 'doc_masalah_2',
    dimension: 'masalah',
    persona: 'doctor',
    text: 'Seberapa siap Anda dengan documentation/medical record requirement untuk international patient (English, export, legal)?',
    options: [
      { label: 'Tidak siap, belum ada process', value: 1 },
      { label: 'Partially siap, ada informal documentation', value: 2 },
      { label: 'Mostly siap, ada basic process tapi ada gap', value: 3 },
      { label: 'Siap baik, ada structured documentation process', value: 4 },
      { label: 'Fully siap dengan comprehensive documentation dan legal compliance', value: 5 },
    ],
  },
  {
    id: 'doc_rough_idea_1',
    dimension: 'rough_idea',
    persona: 'doctor',
    text: 'Apakah Anda sudah punya rough idea tentang target international patient atau specialization focus dalam health tourism?',
    options: [
      { label: 'Tidak ada idea sama sekali', value: 1 },
      { label: 'Ada ide awal, sangat rough', value: 2 },
      { label: 'Ada idea terbentuk tapi belum detail', value: 3 },
      { label: 'Ada clear idea dengan target market identified', value: 4 },
      { label: 'Ada detailed plan dengan positioning dan marketing strategy', value: 5 },
    ],
  },
  {
    id: 'doc_rough_idea_2',
    dimension: 'rough_idea',
    persona: 'doctor',
    text: 'Seberapa urgent kebutuhan Anda untuk support/coaching dari expert dalam health tourism strategy?',
    options: [
      { label: 'Tidak urgent, masih exploratory saja', value: 1 },
      { label: 'Low priority, bisa nanti', value: 2 },
      { label: 'Moderate priority, perlu guidance 6-12 bulan ini', value: 3 },
      { label: 'High priority, perlu coaching 3-6 bulan ini', value: 4 },
      { label: 'Very urgent, perlu immediate mentoring atau minggu ini', value: 5 },
    ],
  },
];

const hotelManagerQuestions: Question[] = [
  {
    id: 'hotel_aset_1',
    dimension: 'aset',
    persona: 'hotel_manager',
    text: 'Seberapa siap fasilitas hotel Anda untuk menerima medical tourists (wellness center, consultation room, medication storage)?',
    options: [
      { label: 'Tidak ada fasilitas khusus, hanya kamar standar', value: 1 },
      { label: 'Ada beberapa fasilitas dasar tapi minimal', value: 2 },
      { label: 'Ada wellness center basic, tidak terintegrasi dengan medis', value: 3 },
      { label: 'Ada wellness + consultation space, belum penuh integrated', value: 4 },
      { label: 'Fully equipped dengan telemedicine + privacy + safety compliance', value: 5 },
    ],
  },
  {
    id: 'hotel_aset_2',
    dimension: 'aset',
    persona: 'hotel_manager',
    text: 'Seberapa kuat partnership hotel Anda dengan fasilitas kesehatan (RS, klinik, dokter) untuk support medical guests?',
    options: [
      { label: 'Tidak ada partnership sama sekali', value: 1 },
      { label: 'Ada kontak informal saja', value: 2 },
      { label: 'Ada partnership basic dengan 1-2 fasilitas', value: 3 },
      { label: 'Ada network kuat dengan 3-5 fasilitas terstruktur', value: 4 },
      { label: 'Ada integrated health concierge dengan network comprehensive', value: 5 },
    ],
  },
  {
    id: 'hotel_potensi_1',
    dimension: 'potensi',
    persona: 'hotel_manager',
    text: 'Berapa persen occupancy rate hotel Anda saat ini? (Indikasi dari potensi kapasitas)',
    options: [
      { label: '<30%, sangat low occupancy', value: 1 },
      { label: '30-50%, moderate tapi ada ruang unused', value: 2 },
      { label: '50-70%, reasonably healthy', value: 3 },
      { label: '70-85%, strong dengan sedikit ruang buffer', value: 4 },
      { label: '>85%, near capacity, siap scale dengan strategic segment', value: 5 },
    ],
  },
  {
    id: 'hotel_potensi_2',
    dimension: 'potensi',
    persona: 'hotel_manager',
    text: 'Seberapa besar potential market dari international guests (diaspora, regional neighbors, medical visa)?',
    options: [
      { label: 'Sangat minimal, local market only', value: 1 },
      { label: 'Ada beberapa international tapi seasonal/irregular', value: 2 },
      { label: 'International presence growing, ada rute stabil', value: 3 },
      { label: 'Significant international, 30-50% dari guests', value: 4 },
      { label: 'Strong international positioning, >50% international with medical segment', value: 5 },
    ],
  },
  {
    id: 'hotel_pengetahuan_1',
    dimension: 'pengetahuan',
    persona: 'hotel_manager',
    text: 'Seberapa familiar tim Anda dengan needs medical tourists (privacy, 24/7 support, medication coordination)?',
    options: [
      { label: 'Tidak familiar, belum pernah handle', value: 1 },
      { label: 'Sedikit familiar dari beberapa guest', value: 2 },
      { label: 'Lumayan familiar, ada basic protocols', value: 3 },
      { label: 'Sangat familiar, sudah trained team dedicated', value: 4 },
      { label: 'Expert level, sudah certified medical hospitality service', value: 5 },
    ],
  },
  {
    id: 'hotel_pengetahuan_2',
    dimension: 'pengetahuan',
    persona: 'hotel_manager',
    text: 'Apakah team Anda bisa komunikasi bahasa inggris/asing untuk coordinating dengan medical professionals?',
    options: [
      { label: 'Tidak, language barrier significant', value: 1 },
      { label: 'Minimal, beberapa staff basic english', value: 2 },
      { label: 'Adequate, front desk dan key staff bisa english', value: 3 },
      { label: 'Strong, most team fluent, ada translator available', value: 4 },
      { label: 'Excellent, multilingual team dengan medical terminology training', value: 5 },
    ],
  },
  {
    id: 'hotel_masalah_1',
    dimension: 'masalah',
    persona: 'hotel_manager',
    text: 'Apa hambatan utama untuk expand market medical tourists?',
    options: [
      { label: 'Banyak hambatan: fasilitas, team, partnership, semua', value: 1 },
      { label: 'Hambatan signifikan di beberapa area (fasilitas atau partnership)', value: 2 },
      { label: 'Hambatan moderate, ada beberapa masalah spesifik', value: 3 },
      { label: 'Minor hambatan, mostly infrastructure dan training', value: 4 },
      { label: 'Minimal hambatan, ready to scale segmentasi medical', value: 5 },
    ],
  },
  {
    id: 'hotel_masalah_2',
    dimension: 'masalah',
    persona: 'hotel_manager',
    text: 'Seberapa siap compliance & insurance hotel untuk handle medical liability risk?',
    options: [
      { label: 'Tidak ada, insurance standard saja', value: 1 },
      { label: 'Minimal, belum aware medical liability risk', value: 2 },
      { label: 'Ada basic insurance, belum comprehensive medical coverage', value: 3 },
      { label: 'Ada medical liability coverage, perlu review', value: 4 },
      { label: 'Full compliance dengan medical liability insurance + waiver system', value: 5 },
    ],
  },
  {
    id: 'hotel_rough_idea_1',
    dimension: 'rough_idea',
    persona: 'hotel_manager',
    text: 'Apakah ada strategi hotel Anda untuk penetrasi medical/wellness tourism market?',
    options: [
      { label: 'Belum ada, baru pikiran', value: 1 },
      { label: 'Ada rough idea, belum actionable', value: 2 },
      { label: 'Ada planning dasar dengan beberapa taktik', value: 3 },
      { label: 'Ada strategy terstruktur, mulai implementasi', value: 4 },
      { label: 'Ada active program dengan marketing spend dan target metric', value: 5 },
    ],
  },
  {
    id: 'hotel_rough_idea_2',
    dimension: 'rough_idea',
    persona: 'hotel_manager',
    text: 'Seberapa urgent kebutuhan Anda untuk partnership atau support dari health tourism expert?',
    options: [
      { label: 'Tidak urgent, exploratory phase', value: 1 },
      { label: 'Low priority, bisa nanti', value: 2 },
      { label: 'Moderate, perlu guidance 6-12 bulan ke depan', value: 3 },
      { label: 'High priority, perlu support immediate 3-6 bulan', value: 4 },
      { label: 'Very urgent, ready untuk intensive collaboration sekarang', value: 5 },
    ],
  },
];

const spaManagerQuestions: Question[] = [
  {
    id: 'spa_aset_1',
    dimension: 'aset',
    persona: 'spa_manager',
    text: 'Seberapa lengkap treatment menu spa Anda (traditional, modern wellness, therapeutic)?',
    options: [
      { label: 'Limited, hanya massage standar', value: 1 },
      { label: 'Basic traditional treatments saja', value: 2 },
      { label: 'Ada beberapa traditional + modern wellness mix', value: 3 },
      { label: 'Comprehensive menu dengan beberapa therapeutic specialty', value: 4 },
      { label: 'Expert-level dengan signature treatments dan medical-grade equipment', value: 5 },
    ],
  },
  {
    id: 'spa_aset_2',
    dimension: 'aset',
    persona: 'spa_manager',
    text: 'Seberapa siap infrastruktur & credential therapists Anda untuk meet international wellness standards?',
    options: [
      { label: 'Minimal, therapist skill level informal', value: 1 },
      { label: 'Basic, ada beberapa trained therapist tapi tidak certified', value: 2 },
      { label: 'Adequate, therapist punya basic certification local', value: 3 },
      { label: 'Strong, team certified international atau specialist training', value: 4 },
      { label: 'Excellent, team expert dengan continuing professional development', value: 5 },
    ],
  },
  {
    id: 'spa_potensi_1',
    dimension: 'potensi',
    persona: 'spa_manager',
    text: 'Berapa persen guests Anda yang international atau dari luar daerah?',
    options: [
      { label: '<10%, mostly local', value: 1 },
      { label: '10-25%, beberapa out-of-town', value: 2 },
      { label: '25-40%, significant share dari external region', value: 3 },
      { label: '40-60%, substantial international/regional presence', value: 4 },
      { label: '>60%, strong international brand positioning', value: 5 },
    ],
  },
  {
    id: 'spa_potensi_2',
    dimension: 'potensi',
    persona: 'spa_manager',
    text: 'Seberapa besar potential untuk develop signature wellness/healing packages untuk medical tourists?',
    options: [
      { label: 'Sangat minimal, treatment saja tanpa package concept', value: 1 },
      { label: 'Ada beberapa bundled packages tapi generic', value: 2 },
      { label: 'Ada wellness package basic, tidak medically-focused', value: 3 },
      { label: 'Ada several themed packages, beberapa health-aligned', value: 4 },
      { label: 'Strong positioning dengan signature medical-wellness packages', value: 5 },
    ],
  },
  {
    id: 'spa_pengetahuan_1',
    dimension: 'pengetahuan',
    persona: 'spa_manager',
    text: 'Seberapa paham Anda dengan health tourism concept dan market opportunity?',
    options: [
      { label: 'Tidak paham, baru dengar', value: 1 },
      { label: 'Sedikit paham dari media/social', value: 2 },
      { label: 'Lumayan paham, pernah riset singkat', value: 3 },
      { label: 'Sangat paham, sudah study market potential', value: 4 },
      { label: 'Expert, sudah punya business model draft', value: 5 },
    ],
  },
  {
    id: 'spa_pengetahuan_2',
    dimension: 'pengetahuan',
    persona: 'spa_manager',
    text: 'Apakah tim Anda punya knowledge tentang therapeutic wellness vs recreational spa?',
    options: [
      { label: 'Tidak ada distinction, semua sama recreational', value: 1 },
      { label: 'Minimal awareness tapi belum deep knowledge', value: 2 },
      { label: 'Adequate understanding, ada beberapa therapeutic elements', value: 3 },
      { label: 'Strong knowledge, therapeutic offerings differentiated', value: 4 },
      { label: 'Expert level, integrated medical-spa protocol dengan therapist training', value: 5 },
    ],
  },
  {
    id: 'spa_masalah_1',
    dimension: 'masalah',
    persona: 'spa_manager',
    text: 'Apa hambatan utama untuk position spa Anda untuk medical/wellness tourism?',
    options: [
      { label: 'Banyak hambatan: treatment, team, marketing, semuanya', value: 1 },
      { label: 'Hambatan signifikan di beberapa area', value: 2 },
      { label: 'Hambatan moderate, ada 2-3 area perlu improvement', value: 3 },
      { label: 'Minor hambatan, mostly marketing dan positioning', value: 4 },
      { label: 'Minimal hambatan, ready untuk differentiate ke medical-wellness', value: 5 },
    ],
  },
  {
    id: 'spa_masalah_2',
    dimension: 'masalah',
    persona: 'spa_manager',
    text: 'Seberapa aware Anda dengan safety/hygiene standard international untuk medical spa?',
    options: [
      { label: 'Tidak aware, follow standard lokal saja', value: 1 },
      { label: 'Minimal aware, tapi belum implementasi', value: 2 },
      { label: 'Aware, ada beberapa standard lokal applied', value: 3 },
      { label: 'Sangat aware, follow international best practice', value: 4 },
      { label: 'Fully compliant dengan certified medical spa safety standard', value: 5 },
    ],
  },
  {
    id: 'spa_rough_idea_1',
    dimension: 'rough_idea',
    persona: 'spa_manager',
    text: 'Apakah ada rough plan spa Anda untuk develop medical/wellness tourism segment?',
    options: [
      { label: 'Belum ada, baru konsep', value: 1 },
      { label: 'Ada ide awal, belum plan formal', value: 2 },
      { label: 'Ada planning dasar, akan start eksperimen', value: 3 },
      { label: 'Ada structured plan, mulai implementasi', value: 4 },
      { label: 'Ada active program dengan target metric dan marketing', value: 5 },
    ],
  },
  {
    id: 'spa_rough_idea_2',
    dimension: 'rough_idea',
    persona: 'spa_manager',
    text: 'Seberapa urgent kebutuhan Anda untuk connect dengan healthcare partners atau expert mentoring?',
    options: [
      { label: 'Tidak urgent, masih exploratory', value: 1 },
      { label: 'Low priority, bisa nanti 1-2 tahun', value: 2 },
      { label: 'Moderate, perlu guidance 6-12 bulan', value: 3 },
      { label: 'High priority, butuh support immediate 3-6 bulan', value: 4 },
      { label: 'Very urgent, ready untuk intensive partnership sekarang', value: 5 },
    ],
  },
];

const resortManagerQuestions: Question[] = [
  {
    id: 'resort_aset_1',
    dimension: 'aset',
    persona: 'resort_manager',
    text: 'Seberapa siap resort Anda untuk integrate health+leisure experience (wellness facilities, medical support, activities)?',
    options: [
      { label: 'Tidak ada integration, leisure only', value: 1 },
      { label: 'Ada beberapa wellness facility tapi isolated dari leisure', value: 2 },
      { label: 'Ada basic integration dengan wellness + leisure mix', value: 3 },
      { label: 'Baik integrated dengan wellness program + activities', value: 4 },
      { label: 'Excellent, fully integrated medical-wellness-leisure ecosystem', value: 5 },
    ],
  },
  {
    id: 'resort_aset_2',
    dimension: 'aset',
    persona: 'resort_manager',
    text: 'Seberapa kuat partnership resort Anda dengan health facilities untuk support health-focused guests?',
    options: [
      { label: 'Tidak ada partnership', value: 1 },
      { label: 'Ada kontak informal saja', value: 2 },
      { label: 'Ada partnership dasar dengan 1-2 klinik', value: 3 },
      { label: 'Ada network terstruktur dengan 3+ facilities', value: 4 },
      { label: 'Integrated health concierge dengan strong medical network', value: 5 },
    ],
  },
  {
    id: 'resort_potensi_1',
    dimension: 'potensi',
    persona: 'resort_manager',
    text: 'Berapa persen dari resort guests yang stay 7+ hari (ideal untuk medical-wellness programs)?',
    options: [
      { label: '<10%, mostly short-term visitors', value: 1 },
      { label: '10-20%, beberapa extended stays', value: 2 },
      { label: '20-35%, reasonable portion extended stays', value: 3 },
      { label: '35-50%, significant long-stay market', value: 4 },
      { label: '>50%, strong positioning untuk immersive programs', value: 5 },
    ],
  },
  {
    id: 'resort_potensi_2',
    dimension: 'potensi',
    persona: 'resort_manager',
    text: 'Seberapa besar potential dari international wellness/medical tourists untuk resort Anda?',
    options: [
      { label: 'Sangat minimal, local market only', value: 1 },
      { label: 'Ada beberapa tapi irregular dan seasonal', value: 2 },
      { label: 'Growing segment dengan beberapa rute established', value: 3 },
      { label: 'Significant presence, 30-50% international guests', value: 4 },
      { label: 'Strong market, >50% international dengan wellness/medical interest', value: 5 },
    ],
  },
  {
    id: 'resort_pengetahuan_1',
    dimension: 'pengetahuan',
    persona: 'resort_manager',
    text: 'Seberapa familiar Anda dengan designing integrated health-leisure programs (itinerary, activities, wellness)?',
    options: [
      { label: 'Tidak familiar, baru konsep', value: 1 },
      { label: 'Sedikit familiar dari industry trend', value: 2 },
      { label: 'Lumayan familiar, ada beberapa program draft', value: 3 },
      { label: 'Sangat familiar, sudah offer beberapa program', value: 4 },
      { label: 'Expert, already operating successful integrated wellness programs', value: 5 },
    ],
  },
  {
    id: 'resort_pengetahuan_2',
    dimension: 'pengetahuan',
    persona: 'resort_manager',
    text: 'Apakah team Anda terlatih untuk coordinate dengan medical professionals untuk guest wellness?',
    options: [
      { label: 'Tidak, belum ada training', value: 1 },
      { label: 'Minimal, belum formal training', value: 2 },
      { label: 'Ada basic training, koordinasi informal', value: 3 },
      { label: 'Trained team dengan protocol terstruktur', value: 4 },
      { label: 'Fully trained dengan certified coordination capability', value: 5 },
    ],
  },
  {
    id: 'resort_masalah_1',
    dimension: 'masalah',
    persona: 'resort_manager',
    text: 'Apa hambatan utama untuk scale health-wellness tourism di resort Anda?',
    options: [
      { label: 'Banyak: partnership, training, program design, marketing', value: 1 },
      { label: 'Hambatan signifikan di beberapa area', value: 2 },
      { label: 'Hambatan moderate, ada beberapa gaps specific', value: 3 },
      { label: 'Minor, mostly marketing dan positioning', value: 4 },
      { label: 'Minimal, ready to scale integrated programs', value: 5 },
    ],
  },
  {
    id: 'resort_masalah_2',
    dimension: 'masalah',
    persona: 'resort_manager',
    text: 'Seberapa aware Anda dengan liability & safety untuk health-focused guests di resort?',
    options: [
      { label: 'Tidak aware, standard leisure insurance saja', value: 1 },
      { label: 'Minimal aware, belum implementasi mitigation', value: 2 },
      { label: 'Aware, ada beberapa precaution', value: 3 },
      { label: 'Sangat aware, insurance + protocol adequate', value: 4 },
      { label: 'Fully compliant dengan health liability coverage + safety protocol', value: 5 },
    ],
  },
  {
    id: 'resort_rough_idea_1',
    dimension: 'rough_idea',
    persona: 'resort_manager',
    text: 'Apakah ada strategy resort untuk develop health-wellness tourism as strategic growth segment?',
    options: [
      { label: 'Belum ada, baru ide', value: 1 },
      { label: 'Ada rough idea, belum actionable', value: 2 },
      { label: 'Ada planning, mulai development', value: 3 },
      { label: 'Ada structured strategy, implementasi underway', value: 4 },
      { label: 'Active program dengan aggressive target dan budget', value: 5 },
    ],
  },
  {
    id: 'resort_rough_idea_2',
    dimension: 'rough_idea',
    persona: 'resort_manager',
    text: 'Seberapa urgent kebutuhan Anda untuk expert partnership atau strategic support?',
    options: [
      { label: 'Tidak urgent, exploratory phase', value: 1 },
      { label: 'Low priority, timeline nanti', value: 2 },
      { label: 'Moderate, perlu guidance 6-12 bulan ke depan', value: 3 },
      { label: 'High priority, butuh support intensive 3-6 bulan', value: 4 },
      { label: 'Very urgent, ready untuk deep collaboration sekarang', value: 5 },
    ],
  },
];

const travelAgentQuestions: Question[] = [
  {
    id: 'ta_aset_1',
    dimension: 'aset',
    persona: 'travel_agent',
    text: 'Seberapa siap travel agency Anda untuk coordinate medical tourism packages (health provider connection, patient journey)?',
    options: [
      { label: 'Tidak siap, belum ada network medical', value: 1 },
      { label: 'Minimal, ada kontak informal saja', value: 2 },
      { label: 'Ada partnership dasar dengan beberapa provider', value: 3 },
      { label: 'Ada network terstruktur dengan clear referral process', value: 4 },
      { label: 'Fully integrated dengan medical concierge service', value: 5 },
    ],
  },
  {
    id: 'ta_aset_2',
    dimension: 'aset',
    persona: 'travel_agent',
    text: 'Seberapa kuat capability travel agency Anda untuk handle visa/documentation untuk medical tourists?',
    options: [
      { label: 'Tidak handle, customer arrange sendiri', value: 1 },
      { label: 'Minimal, basic visa info only', value: 2 },
      { label: 'Ada service dasar, standard visa process', value: 3 },
      { label: 'Ada dedicated team, medical-specific visa knowledge', value: 4 },
      { label: 'Expert, handle complex visa + medical documentation complete', value: 5 },
    ],
  },
  {
    id: 'ta_potensi_1',
    dimension: 'potensi',
    persona: 'travel_agent',
    text: 'Seberapa besar client base travel agency Anda dari diaspora atau international market?',
    options: [
      { label: '<10%, mostly domestic', value: 1 },
      { label: '10-25%, beberapa international clients', value: 2 },
      { label: '25-40%, reasonable international share', value: 3 },
      { label: '40-60%, significant international positioning', value: 4 },
      { label: '>60%, strong international brand dengan diaspora reach', value: 5 },
    ],
  },
  {
    id: 'ta_potensi_2',
    dimension: 'potensi',
    persona: 'travel_agent',
    text: 'Seberapa besar demand dari clients untuk health/wellness travel packages?',
    options: [
      { label: 'Belum ada demand, belum pernah ditanya', value: 1 },
      { label: 'Minimal demand, rare inquiries', value: 2 },
      { label: 'Ada beberapa demand, growing interest', value: 3 },
      { label: 'Significant demand, regular health travel inquiries', value: 4 },
      { label: 'Strong demand, health tourism adalah growing segment', value: 5 },
    ],
  },
  {
    id: 'ta_pengetahuan_1',
    dimension: 'pengetahuan',
    persona: 'travel_agent',
    text: 'Seberapa paham Anda dengan health tourism model dan patient journey?',
    options: [
      { label: 'Tidak paham, baru konsep', value: 1 },
      { label: 'Sedikit paham dari general knowledge', value: 2 },
      { label: 'Lumayan paham, ada basic understanding', value: 3 },
      { label: 'Sangat paham, sudah study patient pathway', value: 4 },
      { label: 'Expert, sudah design custom packages', value: 5 },
    ],
  },
  {
    id: 'ta_pengetahuan_2',
    dimension: 'pengetahuan',
    persona: 'travel_agent',
    text: 'Apakah tim Anda bisa komunikasi dengan healthcare providers dan international patients?',
    options: [
      { label: 'Tidak, language barrier dan medical terminology unfamiliar', value: 1 },
      { label: 'Minimal, basic english saja', value: 2 },
      { label: 'Adequate, team punya english competency', value: 3 },
      { label: 'Strong, fluent english dengan some medical knowledge', value: 4 },
      { label: 'Excellent, multilingual dengan medical coordination capability', value: 5 },
    ],
  },
  {
    id: 'ta_masalah_1',
    dimension: 'masalah',
    persona: 'travel_agent',
    text: 'Apa hambatan utama untuk expand ke medical tourism business model?',
    options: [
      { label: 'Banyak: network, knowledge, resources, semuanya', value: 1 },
      { label: 'Hambatan signifikan di partnership dan knowledge', value: 2 },
      { label: 'Hambatan moderate, ada beberapa gaps', value: 3 },
      { label: 'Minor, mostly marketing dan client education', value: 4 },
      { label: 'Minimal, ready untuk launch medical tourism services', value: 5 },
    ],
  },
  {
    id: 'ta_masalah_2',
    dimension: 'masalah',
    persona: 'travel_agent',
    text: 'Seberapa awareness Anda dengan commission/revenue model untuk medical tourism?',
    options: [
      { label: 'Tidak aware, standard travel commission saja', value: 1 },
      { label: 'Minimal aware, belum clear revenue stream', value: 2 },
      { label: 'Adequate, ada some understanding dari research', value: 3 },
      { label: 'Strong, sudah calculate potential margin', value: 4 },
      { label: 'Clear business model dengan negotiated revenue share', value: 5 },
    ],
  },
  {
    id: 'ta_rough_idea_1',
    dimension: 'rough_idea',
    persona: 'travel_agent',
    text: 'Apakah ada plan travel agency untuk develop medical tourism as new service offering?',
    options: [
      { label: 'Belum ada, baru interest', value: 1 },
      { label: 'Ada rough idea, belum actionable', value: 2 },
      { label: 'Ada planning, akan start pilot', value: 3 },
      { label: 'Ada structured plan, mulai implementation', value: 4 },
      { label: 'Active program dengan package design dan target clients', value: 5 },
    ],
  },
  {
    id: 'ta_rough_idea_2',
    dimension: 'rough_idea',
    persona: 'travel_agent',
    text: 'Seberapa urgent kebutuhan Anda untuk connect dengan healthcare partners dan expert guidance?',
    options: [
      { label: 'Tidak urgent, masih exploratory', value: 1 },
      { label: 'Low priority, bisa nanti', value: 2 },
      { label: 'Moderate, perlu guidance 6-12 bulan', value: 3 },
      { label: 'High priority, butuh partnership intensive 3-6 bulan', value: 4 },
      { label: 'Very urgent, ready untuk immediate collaboration', value: 5 },
    ],
  },
];

const youthLeaderQuestions: Question[] = [
  {
    id: 'youth_aset_1',
    dimension: 'aset',
    persona: 'youth_leader',
    text: 'Seberapa kuat resource & network pemuda daerah Anda untuk support health tourism initiative?',
    options: [
      { label: 'Sangat terbatas, mostly informal gathering', value: 1 },
      { label: 'Ada basic structure tapi resource minimal', value: 2 },
      { label: 'Ada organizational structure dengan beberapa resource', value: 3 },
      { label: 'Strong organization dengan good resource access', value: 4 },
      { label: 'Excellent network dengan strong leadership dan resource base', value: 5 },
    ],
  },
  {
    id: 'youth_aset_2',
    dimension: 'aset',
    persona: 'youth_leader',
    text: 'Seberapa siap pemuda daerah untuk engage dalam business/entrepreneurship (vs social activity saja)?',
    options: [
      { label: 'Belum siap, social focus only', value: 1 },
      { label: 'Ada beberapa interest entrepreneurship tapi belum trained', value: 2 },
      { label: 'Ada beberapa member dengan entrepreneurship interest', value: 3 },
      { label: 'Banyak member siap, ada basic training', value: 4 },
      { label: 'Well-trained group, siap untuk business venture', value: 5 },
    ],
  },
  {
    id: 'youth_potensi_1',
    dimension: 'potensi',
    persona: 'youth_leader',
    text: 'Berapa banyak anggota pemuda daerah Anda yang aktif dan bisa engage dalam health tourism project?',
    options: [
      { label: '<20, very small group', value: 1 },
      { label: '20-50, small but engaged group', value: 2 },
      { label: '50-100, moderate size group', value: 3 },
      { label: '100-200, significant organization', value: 4 },
      { label: '>200, large community dengan high engagement', value: 5 },
    ],
  },
  {
    id: 'youth_potensi_2',
    dimension: 'potensi',
    persona: 'youth_leader',
    text: 'Seberapa besar potensi pemuda daerah untuk menjadi brand ambassador atau guide untuk health tourism?',
    options: [
      { label: 'Sangat minimal, skill vs formal', value: 1 },
      { label: 'Ada potensi tapi perlu training significant', value: 2 },
      { label: 'Reasonable potential dengan beberapa training', value: 3 },
      { label: 'Strong potential, mostly ready dengan minor training', value: 4 },
      { label: 'Excellent, bisa langsung jadi ambassador/guide professional', value: 5 },
    ],
  },
  {
    id: 'youth_pengetahuan_1',
    dimension: 'pengetahuan',
    persona: 'youth_leader',
    text: 'Seberapa paham pemuda daerah tentang health tourism concept dan opportunity?',
    options: [
      { label: 'Tidak paham, baru dengar', value: 1 },
      { label: 'Sedikit paham dari social media', value: 2 },
      { label: 'Lumayan paham, ada beberapa awareness', value: 3 },
      { label: 'Sangat paham, sudah diskusi dalam group', value: 4 },
      { label: 'Expert awareness, sudah punya project draft', value: 5 },
    ],
  },
  {
    id: 'youth_pengetahuan_2',
    dimension: 'pengetahuan',
    persona: 'youth_leader',
    text: 'Apakah ada expertise dalam community dalam hospitality atau service excellence?',
    options: [
      { label: 'Tidak ada, belum familiar', value: 1 },
      { label: 'Minimal, belum organized training', value: 2 },
      { label: 'Ada beberapa basic hospitality awareness', value: 3 },
      { label: 'Ada trained members, service culture starting', value: 4 },
      { label: 'Strong service expertise, ready untuk international standard', value: 5 },
    ],
  },
  {
    id: 'youth_masalah_1',
    dimension: 'masalah',
    persona: 'youth_leader',
    text: 'Apa hambatan utama dalam mengorganisir pemuda daerah untuk health tourism project?',
    options: [
      { label: 'Banyak hambatan: engagement, resource, knowledge, leadership', value: 1 },
      { label: 'Hambatan signifikan di coordination dan resource', value: 2 },
      { label: 'Hambatan moderate, ada beberapa masalah spesifik', value: 3 },
      { label: 'Minor hambatan, mostly training dan positioning', value: 4 },
      { label: 'Minimal, komunitas ready untuk mobilize', value: 5 },
    ],
  },
  {
    id: 'youth_masalah_2',
    dimension: 'masalah',
    persona: 'youth_leader',
    text: 'Seberapa sustainable model untuk engage pemuda (incentive, profit sharing, career path)?',
    options: [
      { label: 'Belum ada model, voluntary saja', value: 1 },
      { label: 'Ada beberapa incentive informal', value: 2 },
      { label: 'Ada basic incentive structure, belum sustainable', value: 3 },
      { label: 'Ada profit sharing model, reasonably sustainable', value: 4 },
      { label: 'Clear business model dengan good career path untuk members', value: 5 },
    ],
  },
  {
    id: 'youth_rough_idea_1',
    dimension: 'rough_idea',
    persona: 'youth_leader',
    text: 'Apakah ada vision/roadmap untuk pemuda daerah dalam health tourism initiative?',
    options: [
      { label: 'Belum ada, baru idea', value: 1 },
      { label: 'Ada vague idea, belum terstruktur', value: 2 },
      { label: 'Ada planning dasar dengan beberapa milestone', value: 3 },
      { label: 'Ada roadmap terstruktur, mulai execution', value: 4 },
      { label: 'Ada detailed roadmap dengan active implementation', value: 5 },
    ],
  },
  {
    id: 'youth_rough_idea_2',
    dimension: 'rough_idea',
    persona: 'youth_leader',
    text: 'Seberapa urgent kebutuhan untuk mentoring/support dari external expert?',
    options: [
      { label: 'Tidak urgent, belum siap', value: 1 },
      { label: 'Low priority, perlu waktu persiapan internal', value: 2 },
      { label: 'Moderate, perlu guidance 6-12 bulan', value: 3 },
      { label: 'High priority, butuh intensive support 3-6 bulan', value: 4 },
      { label: 'Very urgent, ready untuk deep mentoring sekarang', value: 5 },
    ],
  },
];

const karangTarunaLeaderQuestions: Question[] = [
  {
    id: 'kt_aset_1',
    dimension: 'aset',
    persona: 'karang_taruna_leader',
    text: 'Seberapa terstruktur organisasi Karang Taruna Anda (management, regularity meeting, accountability)?',
    options: [
      { label: 'Sangat informal, barely organized', value: 1 },
      { label: 'Ada basic structure tapi loose implementation', value: 2 },
      { label: 'Ada solid organizational structure, regular activity', value: 3 },
      { label: 'Well-structured dengan strong management', value: 4 },
      { label: 'Excellent organizational maturity dengan governance formal', value: 5 },
    ],
  },
  {
    id: 'kt_aset_2',
    dimension: 'aset',
    persona: 'karang_taruna_leader',
    text: 'Seberapa kuat trust & social capital Karang Taruna di komunitas lokal?',
    options: [
      { label: 'Minimal, belum recognized', value: 1 },
      { label: 'Ada beberapa recognition lokal', value: 2 },
      { label: 'Recognized di community, trusted untuk beberapa project', value: 3 },
      { label: 'Strong trust, community sering refer kepada Karang Taruna', value: 4 },
      { label: 'Excellent reputation, primary trusted institution di village', value: 5 },
    ],
  },
  {
    id: 'kt_potensi_1',
    dimension: 'potensi',
    persona: 'karang_taruna_leader',
    text: 'Berapa jumlah anggota aktif Karang Taruna Anda yang bisa mobilize untuk project?',
    options: [
      { label: '<30, sangat kecil', value: 1 },
      { label: '30-60, small group', value: 2 },
      { label: '60-150, moderate size', value: 3 },
      { label: '150-300, significant organization', value: 4 },
      { label: '>300, large community dengan high engagement', value: 5 },
    ],
  },
  {
    id: 'kt_potensi_2',
    dimension: 'potensi',
    persona: 'karang_taruna_leader',
    text: 'Seberapa besar skill diversity dalam Karang Taruna untuk support health tourism (guide, hospitality, coordination)?',
    options: [
      { label: 'Minimal diversity, mostly unskilled', value: 1 },
      { label: 'Ada beberapa skill tapi terbatas', value: 2 },
      { label: 'Reasonable diversity, beberapa trained member', value: 3 },
      { label: 'Good diversity dengan well-trained team', value: 4 },
      { label: 'Excellent diversity, professional-level skill available', value: 5 },
    ],
  },
  {
    id: 'kt_pengetahuan_1',
    dimension: 'pengetahuan',
    persona: 'karang_taruna_leader',
    text: 'Seberapa paham Karang Taruna tentang health tourism dan potensi di komunitas?',
    options: [
      { label: 'Tidak paham, baru konsep', value: 1 },
      { label: 'Sedikit paham dari perbincangan', value: 2 },
      { label: 'Lumayan paham, ada awareness dalam group', value: 3 },
      { label: 'Sangat paham, sudah diskusi mendalam', value: 4 },
      { label: 'Expert understanding, sudah punya project proposal draft', value: 5 },
    ],
  },
  {
    id: 'kt_pengetahuan_2',
    dimension: 'pengetahuan',
    persona: 'karang_taruna_leader',
    text: 'Apakah ada training/certification dalam Karang Taruna untuk hospitality atau service excellence?',
    options: [
      { label: 'Tidak ada, belum ada program', value: 1 },
      { label: 'Ada interest tapi belum training', value: 2 },
      { label: 'Ada basic training untuk beberapa member', value: 3 },
      { label: 'Ada structured training program dengan certification', value: 4 },
      { label: 'Comprehensive training dengan continuous professional development', value: 5 },
    ],
  },
  {
    id: 'kt_masalah_1',
    dimension: 'masalah',
    persona: 'karang_taruna_leader',
    text: 'Apa hambatan utama untuk Karang Taruna engage dalam health tourism initiative?',
    options: [
      { label: 'Banyak hambatan: knowledge, resource, skill, connection', value: 1 },
      { label: 'Hambatan signifikan di beberapa area', value: 2 },
      { label: 'Hambatan moderate, ada spesifik masalah', value: 3 },
      { label: 'Minor hambatan, mostly training dan connection', value: 4 },
      { label: 'Minimal, organization ready untuk engage', value: 5 },
    ],
  },
  {
    id: 'kt_masalah_2',
    dimension: 'masalah',
    persona: 'karang_taruna_leader',
    text: 'Seberapa clear revenue/sustainability model untuk Karang Taruna dalam health tourism project?',
    options: [
      { label: 'Tidak clear, belum ada model', value: 1 },
      { label: 'Ada vague idea, belum detailed', value: 2 },
      { label: 'Ada basic model, perlu refinement', value: 3 },
      { label: 'Ada clear model dengan reasonable margin', value: 4 },
      { label: 'Excellent model, sustainable dengan community benefit', value: 5 },
    ],
  },
  {
    id: 'kt_rough_idea_1',
    dimension: 'rough_idea',
    persona: 'karang_taruna_leader',
    text: 'Apakah ada plan Karang Taruna untuk health tourism sebagai income-generating activity?',
    options: [
      { label: 'Belum ada, baru pikiran', value: 1 },
      { label: 'Ada ide awal, belum detail', value: 2 },
      { label: 'Ada planning dasar, akan mulai pilot', value: 3 },
      { label: 'Ada structured plan, mulai execution', value: 4 },
      { label: 'Active program dengan measurable target', value: 5 },
    ],
  },
  {
    id: 'kt_rough_idea_2',
    dimension: 'rough_idea',
    persona: 'karang_taruna_leader',
    text: 'Seberapa urgent kebutuhan untuk external support/partnership untuk scale initiative?',
    options: [
      { label: 'Tidak urgent, belum ready', value: 1 },
      { label: 'Low priority, perlu internal preparation', value: 2 },
      { label: 'Moderate, perlu guidance 6-12 bulan', value: 3 },
      { label: 'High priority, butuh support intensive 3-6 bulan', value: 4 },
      { label: 'Very urgent, ready untuk immediate partnership', value: 5 },
    ],
  },
];

const villageHeadQuestions: Question[] = [
  {
    id: 'vh_aset_1',
    dimension: 'aset',
    persona: 'village_head',
    text: 'Seberapa siap infrastruktur desa Anda (jalan, transportasi, listrik, internet) untuk receive tourists?',
    options: [
      { label: 'Sangat minimal, perlu significant upgrade', value: 1 },
      { label: 'Ada basic tapi usang, perlu improvement', value: 2 },
      { label: 'Adequate untuk local tourism, perlu upgrade untuk regional', value: 3 },
      { label: 'Baik, memadai untuk tourism development', value: 4 },
      { label: 'Excellent, ready untuk international standard tourism', value: 5 },
    ],
  },
  {
    id: 'vh_aset_2',
    dimension: 'aset',
    persona: 'village_head',
    text: 'Seberapa kuat komitmen komunitas desa untuk engage dalam health tourism (tidak hanya pimpinan)?',
    options: [
      { label: 'Sangat rendah, community belum interested', value: 1 },
      { label: 'Ada beberapa interest tapi skeptical', value: 2 },
      { label: 'Reasonable interest, ada buy-in dari beberapa groups', value: 3 },
      { label: 'Strong support, community engaged dan proaktif', value: 4 },
      { label: 'Excellent community support, enthusiastic participation', value: 5 },
    ],
  },
  {
    id: 'vh_potensi_1',
    dimension: 'potensi',
    persona: 'village_head',
    text: 'Seberapa besar potensi atraksi natural/cultural di desa Anda untuk health tourism?',
    options: [
      { label: 'Minimal, tidak ada special attractions', value: 1 },
      { label: 'Ada beberapa tapi belum dikembangkan', value: 2 },
      { label: 'Ada attraction cukup baik, dapat develop', value: 3 },
      { label: 'Kuat, already developed attractions', value: 4 },
      { label: 'Excellent, signature attractions dengan international appeal', value: 5 },
    ],
  },
  {
    id: 'vh_potensi_2',
    dimension: 'potensi',
    persona: 'village_head',
    text: 'Seberapa besar potensi accommodation (homestay, guesthouse) di desa untuk tourists?',
    options: [
      { label: 'Sangat minimal, almost tidak ada', value: 1 },
      { label: 'Ada beberapa homestay, capacity terbatas', value: 2 },
      { label: 'Ada beberapa option, reasonable capacity', value: 3 },
      { label: 'Good accommodation option, capacity adequate', value: 4 },
      { label: 'Strong accommodation ecosystem dengan professional management', value: 5 },
    ],
  },
  {
    id: 'vh_pengetahuan_1',
    dimension: 'pengetahuan',
    persona: 'village_head',
    text: 'Seberapa paham Kepala Desa tentang health tourism model dan benefit ekonomi lokal?',
    options: [
      { label: 'Tidak paham, baru konsep', value: 1 },
      { label: 'Sedikit paham dari perbincangan', value: 2 },
      { label: 'Lumayan paham, ada understanding dasar', value: 3 },
      { label: 'Sangat paham, sudah pelajari model', value: 4 },
      { label: 'Expert understanding, sudah punya vision untuk desa', value: 5 },
    ],
  },
  {
    id: 'vh_pengetahuan_2',
    dimension: 'pengetahuan',
    persona: 'village_head',
    text: 'Apakah ada regulatory/administrative preparedness untuk tourism di desa (permits, safety, etc)?',
    options: [
      { label: 'Tidak ada, belum ada sistem', value: 1 },
      { label: 'Ada basic lokal tapi belum formal', value: 2 },
      { label: 'Ada beberapa regulation, belum comprehensive', value: 3 },
      { label: 'Ada structured regulation dengan enforcement', value: 4 },
      { label: 'Excellent compliance framework dengan formal monitoring', value: 5 },
    ],
  },
  {
    id: 'vh_masalah_1',
    dimension: 'masalah',
    persona: 'village_head',
    text: 'Apa hambatan utama untuk develop health tourism di desa?',
    options: [
      { label: 'Banyak hambatan: infra, awareness, resources, regulatory', value: 1 },
      { label: 'Hambatan signifikan di beberapa area', value: 2 },
      { label: 'Hambatan moderate, ada specific masalah', value: 3 },
      { label: 'Minor hambatan, mostly execution dan scaling', value: 4 },
      { label: 'Minimal hambatan, desa ready untuk development', value: 5 },
    ],
  },
  {
    id: 'vh_masalah_2',
    dimension: 'masalah',
    persona: 'village_head',
    text: 'Seberapa aware Anda dengan economic benefit vs social disruption dari tourism?',
    options: [
      { label: 'Tidak aware, belum pikir masalah sosial', value: 1 },
      { label: 'Sedikit aware, fokus benefit saja', value: 2 },
      { label: 'Adequate awareness, ada plan untuk mitigate', value: 3 },
      { label: 'Sangat aware, sudah plan community protection', value: 4 },
      { label: 'Excellent balance, model yang sustainable untuk community', value: 5 },
    ],
  },
  {
    id: 'vh_rough_idea_1',
    dimension: 'rough_idea',
    persona: 'village_head',
    text: 'Apakah ada vision/rencana desa untuk health tourism development?',
    options: [
      { label: 'Belum ada, baru ide', value: 1 },
      { label: 'Ada rough idea, belum formal', value: 2 },
      { label: 'Ada planning dasar dengan outline', value: 3 },
      { label: 'Ada rencana terstruktur, mulai implementasi', value: 4 },
      { label: 'Ada detailed roadmap dengan active execution', value: 5 },
    ],
  },
  {
    id: 'vh_rough_idea_2',
    dimension: 'rough_idea',
    persona: 'village_head',
    text: 'Seberapa urgent kebutuhan untuk expert support/mentoring dalam development?',
    options: [
      { label: 'Tidak urgent, masih planning phase', value: 1 },
      { label: 'Low priority, timeline nanti', value: 2 },
      { label: 'Moderate, perlu guidance 6-12 bulan ke depan', value: 3 },
      { label: 'High priority, butuh support intensive 3-6 bulan', value: 4 },
      { label: 'Very urgent, ready untuk immediate collaboration', value: 5 },
    ],
  },
];

const tourismManagerQuestions: Question[] = [
  {
    id: 'tm_aset_1',
    dimension: 'aset',
    persona: 'tourism_manager',
    text: 'Seberapa baik infrastructure & facilities di destinasi tourism Anda untuk support health tourists?',
    options: [
      { label: 'Minimal, mostly leisure-focused', value: 1 },
      { label: 'Ada basic facilities, tidak terintegrasi health', value: 2 },
      { label: 'Ada fasilitas adequate, mulai integrate health component', value: 3 },
      { label: 'Baik, ada integrated health+leisure facilities', value: 4 },
      { label: 'Excellent, fully developed health-tourism ecosystem', value: 5 },
    ],
  },
  {
    id: 'tm_aset_2',
    dimension: 'aset',
    persona: 'tourism_manager',
    text: 'Seberapa kuat partnership destination Anda dengan health facilities dan accommodation providers?',
    options: [
      { label: 'Minimal, barely any coordination', value: 1 },
      { label: 'Ada loose network', value: 2 },
      { label: 'Ada coordination structured dengan beberapa partner', value: 3 },
      { label: 'Strong network dengan integrated planning', value: 4 },
      { label: 'Excellent ecosystem dengan formal partnership agreement', value: 5 },
    ],
  },
  {
    id: 'tm_potensi_1',
    dimension: 'potensi',
    persona: 'tourism_manager',
    text: 'Berapa banyak visitors annually ke destinasi tourism Anda? (Scale indikator)',
    options: [
      { label: '<100k, still developing destination', value: 1 },
      { label: '100k-500k, growing destination', value: 2 },
      { label: '500k-1M, established destination', value: 3 },
      { label: '1M-3M, popular destination', value: 4 },
      { label: '>3M, major destination dengan international scale', value: 5 },
    ],
  },
  {
    id: 'tm_potensi_2',
    dimension: 'potensi',
    persona: 'tourism_manager',
    text: 'Seberapa besar percentage dari visitors yang interested dalam wellness/health activities?',
    options: [
      { label: '<5%, minimal wellness interest', value: 1 },
      { label: '5-15%, growing wellness segment', value: 2 },
      { label: '15-30%, reasonable wellness interest', value: 3 },
      { label: '30-50%, significant wellness market', value: 4 },
      { label: '>50%, strong wellness-focused destination', value: 5 },
    ],
  },
  {
    id: 'tm_pengetahuan_1',
    dimension: 'pengetahuan',
    persona: 'tourism_manager',
    text: 'Seberapa familiar Anda dengan health tourism model dan market trends?',
    options: [
      { label: 'Tidak familiar, baru konsep', value: 1 },
      { label: 'Sedikit familiar dari industry discussion', value: 2 },
      { label: 'Lumayan familiar, ada basic knowledge', value: 3 },
      { label: 'Sangat familiar, sudah study market', value: 4 },
      { label: 'Expert, sudah punya strategic positioning', value: 5 },
    ],
  },
  {
    id: 'tm_pengetahuan_2',
    dimension: 'pengetahuan',
    persona: 'tourism_manager',
    text: 'Apakah ada training untuk tour guides tentang health tourism & wellness services?',
    options: [
      { label: 'Tidak ada training', value: 1 },
      { label: 'Ada interest tapi belum training formal', value: 2 },
      { label: 'Ada basic training untuk beberapa guide', value: 3 },
      { label: 'Ada structured training untuk team', value: 4 },
      { label: 'Comprehensive training dengan certification program', value: 5 },
    ],
  },
  {
    id: 'tm_masalah_1',
    dimension: 'masalah',
    persona: 'tourism_manager',
    text: 'Apa hambatan utama untuk develop health tourism segment di destinasi?',
    options: [
      { label: 'Banyak hambatan: partnership, knowledge, infrastructure', value: 1 },
      { label: 'Hambatan signifikan di beberapa area', value: 2 },
      { label: 'Hambatan moderate, ada spesifik gaps', value: 3 },
      { label: 'Minor hambatan, mostly marketing dan coordination', value: 4 },
      { label: 'Minimal hambatan, ready untuk aggressive health tourism marketing', value: 5 },
    ],
  },
  {
    id: 'tm_masalah_2',
    dimension: 'masalah',
    persona: 'tourism_manager',
    text: 'Seberapa aware Anda dengan quality assurance & safety untuk health-focused tourism?',
    options: [
      { label: 'Tidak aware, standard leisure tourism saja', value: 1 },
      { label: 'Minimal aware, belum implement', value: 2 },
      { label: 'Adequate awareness, ada beberapa quality protocol', value: 3 },
      { label: 'Sangat aware, implemented quality standard', value: 4 },
      { label: 'Excellent, certified health tourism quality assurance', value: 5 },
    ],
  },
  {
    id: 'tm_rough_idea_1',
    dimension: 'rough_idea',
    persona: 'tourism_manager',
    text: 'Apakah ada strategic plan untuk position destinasi sebagai health tourism hub?',
    options: [
      { label: 'Belum ada, baru ide', value: 1 },
      { label: 'Ada rough idea, belum actionable', value: 2 },
      { label: 'Ada planning dasar dengan some initiatives', value: 3 },
      { label: 'Ada structured strategy, active implementation', value: 4 },
      { label: 'Comprehensive strategy dengan major marketing investment', value: 5 },
    ],
  },
  {
    id: 'tm_rough_idea_2',
    dimension: 'rough_idea',
    persona: 'tourism_manager',
    text: 'Seberapa urgent kebutuhan untuk partnership dengan health providers & expert?',
    options: [
      { label: 'Tidak urgent, exploratory saja', value: 1 },
      { label: 'Low priority, bisa nanti', value: 2 },
      { label: 'Moderate, perlu guidance 6-12 bulan', value: 3 },
      { label: 'High priority, butuh intensive support 3-6 bulan', value: 4 },
      { label: 'Very urgent, ready untuk strategic partnership sekarang', value: 5 },
    ],
  },
];

const nationalParkManagerQuestions: Question[] = [
  {
    id: 'npm_aset_1',
    dimension: 'aset',
    persona: 'national_park_manager',
    text: 'Seberapa siap national park Anda untuk support health+wellness activities (trails, facilities, guides)?',
    options: [
      { label: 'Minimal, basic conservation focus saja', value: 1 },
      { label: 'Ada beberapa facilities tapi belum wellness-focused', value: 2 },
      { label: 'Ada adequate facilities, dapat develop wellness activities', value: 3 },
      { label: 'Baik, ada integrated health+nature activities', value: 4 },
      { label: 'Excellent, fully developed wellness ecosystem', value: 5 },
    ],
  },
  {
    id: 'npm_aset_2',
    dimension: 'aset',
    persona: 'national_park_manager',
    text: 'Seberapa kuat partnership park Anda dengan accommodation dan health services?',
    options: [
      { label: 'Minimal, barely any partnership', value: 1 },
      { label: 'Ada informal coordination', value: 2 },
      { label: 'Ada structured partnership dengan beberapa provider', value: 3 },
      { label: 'Strong network dengan integrated service delivery', value: 4 },
      { label: 'Excellent ecosystem dengan formal MOU', value: 5 },
    ],
  },
  {
    id: 'npm_potensi_1',
    dimension: 'potensi',
    persona: 'national_park_manager',
    text: 'Seberapa besar visitor volume nasional park annually? (Skala indikator)',
    options: [
      { label: '<100k, developing park', value: 1 },
      { label: '100k-500k, growing park', value: 2 },
      { label: '500k-1M, established park', value: 3 },
      { label: '1M-3M, major park destination', value: 4 },
      { label: '>3M, international-scale destination', value: 5 },
    ],
  },
  {
    id: 'npm_potensi_2',
    dimension: 'potensi',
    persona: 'national_park_manager',
    text: 'Seberapa besar percentage dari visitors dengan interest dalam health/wellness activities?',
    options: [
      { label: '<5%, minimal wellness interest', value: 1 },
      { label: '5-15%, growing wellness segment', value: 2 },
      { label: '15-30%, reasonable wellness interest', value: 3 },
      { label: '30-50%, significant wellness demand', value: 4 },
      { label: '>50%, strong nature-wellness destination', value: 5 },
    ],
  },
  {
    id: 'npm_pengetahuan_1',
    dimension: 'pengetahuan',
    persona: 'national_park_manager',
    text: 'Seberapa familiar Anda dengan health tourism & wellness market trends?',
    options: [
      { label: 'Tidak familiar, conservation-focused saja', value: 1 },
      { label: 'Sedikit familiar dari industry discussion', value: 2 },
      { label: 'Lumayan familiar, ada understanding dasar', value: 3 },
      { label: 'Sangat familiar, sudah riset positioning', value: 4 },
      { label: 'Expert, sudah integrated dalam park strategy', value: 5 },
    ],
  },
  {
    id: 'npm_pengetahuan_2',
    dimension: 'pengetahuan',
    persona: 'national_park_manager',
    text: 'Apakah ada training untuk park guides tentang health/wellness aspect dari nature experience?',
    options: [
      { label: 'Tidak ada, conservation guide saja', value: 1 },
      { label: 'Ada interest tapi belum training', value: 2 },
      { label: 'Ada basic wellness training untuk beberapa guide', value: 3 },
      { label: 'Ada structured training untuk team', value: 4 },
      { label: 'Comprehensive health-nature guide training dengan certification', value: 5 },
    ],
  },
  {
    id: 'npm_masalah_1',
    dimension: 'masalah',
    persona: 'national_park_manager',
    text: 'Apa hambatan utama untuk develop health tourism di national park?',
    options: [
      { label: 'Banyak hambatan: conservation conflict, partnership, training', value: 1 },
      { label: 'Hambatan signifikan di coordination dan capacity', value: 2 },
      { label: 'Hambatan moderate, ada specific gaps', value: 3 },
      { label: 'Minor hambatan, mostly marketing dan guide training', value: 4 },
      { label: 'Minimal hambatan, ready untuk health tourism positioning', value: 5 },
    ],
  },
  {
    id: 'npm_masalah_2',
    dimension: 'masalah',
    persona: 'national_park_manager',
    text: 'Seberapa balanced approach park Anda antara conservation vs tourism development?',
    options: [
      { label: 'Heavy conservation bias, minimal tourism consideration', value: 1 },
      { label: 'Conservation-focused, limited tourism expansion', value: 2 },
      { label: 'Moderate balance, some sustainable tourism', value: 3 },
      { label: 'Good balance, integrated conservation-tourism model', value: 4 },
      { label: 'Excellent, proven sustainable health tourism compatible conservation', value: 5 },
    ],
  },
  {
    id: 'npm_rough_idea_1',
    dimension: 'rough_idea',
    persona: 'national_park_manager',
    text: 'Apakah ada strategic vision untuk integrate health/wellness tourism dalam park management?',
    options: [
      { label: 'Belum ada, conservation priority only', value: 1 },
      { label: 'Ada rough idea, belum formal planning', value: 2 },
      { label: 'Ada basic plan dengan some initiatives', value: 3 },
      { label: 'Ada structured strategy, mulai implementation', value: 4 },
      { label: 'Comprehensive vision dengan integrated programming', value: 5 },
    ],
  },
  {
    id: 'npm_rough_idea_2',
    dimension: 'rough_idea',
    persona: 'national_park_manager',
    text: 'Seberapa urgent kebutuhan untuk expert partnership dalam health tourism development?',
    options: [
      { label: 'Tidak urgent, belum dalam priority', value: 1 },
      { label: 'Low priority, exploratory phase', value: 2 },
      { label: 'Moderate, perlu guidance 6-12 bulan ke depan', value: 3 },
      { label: 'High priority, butuh intensive support 3-6 bulan', value: 4 },
      { label: 'Very urgent, ready untuk strategic partnership sekarang', value: 5 },
    ],
  },
];

const byanmaraQuestions: Question[] = [
  {
    id: 'byan_aset_1',
    dimension: 'aset',
    persona: 'byanmara',
    text: 'Seberapa siap organisasi/proyekmu untuk implement regenerative tourism framework?',
    options: [
      { label: 'Belum siap, masih konsep', value: 1 },
      { label: 'Ada beberapa element, belum integrated framework', value: 2 },
      { label: 'Ada framework dasar, implementasi parsial', value: 3 },
      { label: 'Framework terstruktur, active implementation', value: 4 },
      { label: 'Fully integrated regenerative model dengan proven impact', value: 5 },
    ],
  },
  {
    id: 'byan_aset_2',
    dimension: 'aset',
    persona: 'byanmara',
    text: 'Seberapa dalam expertise Anda dalam blue carbon/coastal restoration untuk tourism context?',
    options: [
      { label: 'Minimal, general ESG knowledge saja', value: 1 },
      { label: 'Beberapa project experience, belum deep expertise', value: 2 },
      { label: 'Solid understanding, beberapa successful project', value: 3 },
      { label: 'Strong expertise, multiple validated projects', value: 4 },
      { label: 'Deep expert, publications/awards, thought leader', value: 5 },
    ],
  },
  {
    id: 'byan_potensi_1',
    dimension: 'potensi',
    persona: 'byanmara',
    text: 'Seberapa besar network Anda dengan conservation organizations & blue economy players?',
    options: [
      { label: 'Minimal, mostly academic network', value: 1 },
      { label: 'Ada beberapa contacts, belum strong relationship', value: 2 },
      { label: 'Reasonable network dengan beberapa key partner', value: 3 },
      { label: 'Strong network dengan active collaborations', value: 4 },
      { label: 'Extensive network dengan strategic partnership ecosystem', value: 5 },
    ],
  },
  {
    id: 'byan_potensi_2',
    dimension: 'potensi',
    persona: 'byanmara',
    text: 'Seberapa besar potential untuk monetize blue carbon/regenerative impact di tourism context?',
    options: [
      { label: 'Minimal, belum clear business model', value: 1 },
      { label: 'Ada some idea, belum validated', value: 2 },
      { label: 'Ada several potential models, need testing', value: 3 },
      { label: 'Beberapa model viable, beberapa pilot running', value: 4 },
      { label: 'Clear monetization strategy dengan proven revenue stream', value: 5 },
    ],
  },
  {
    id: 'byan_pengetahuan_1',
    dimension: 'pengetahuan',
    persona: 'byanmara',
    text: 'Seberapa dalam understanding tentang health tourism intersection dengan regenerative/blue economy?',
    options: [
      { label: 'Minimal, separate domain untuk Anda', value: 1 },
      { label: 'Ada awareness, belum integrated thinking', value: 2 },
      { label: 'Reasonable understanding, mulai see synergy', value: 3 },
      { label: 'Strong understanding, sudah identify opportunities', value: 4 },
      { label: 'Expert integration, sudah design convergence strategy', value: 5 },
    ],
  },
  {
    id: 'byan_pengetahuan_2',
    dimension: 'pengetahuan',
    persona: 'byanmara',
    text: 'Apakah Anda familiar dengan ESG reporting frameworks & carbon credit mechanisms untuk tourism?',
    options: [
      { label: 'Minimal, general knowledge saja', value: 1 },
      { label: 'Ada some familiarity, belum detailed', value: 2 },
      { label: 'Adequate knowledge, ada beberapa project experience', value: 3 },
      { label: 'Strong knowledge, implemented reporting system', value: 4 },
      { label: 'Expert, published guidance/certified framework', value: 5 },
    ],
  },
  {
    id: 'byan_masalah_1',
    dimension: 'masalah',
    persona: 'byanmara',
    text: 'Apa hambatan utama untuk integrate regenerative tourism dengan healthcare stakeholders?',
    options: [
      { label: 'Banyak: language barrier, culture gap, incentive mismatch', value: 1 },
      { label: 'Hambatan signifikan dalam coordination & interest alignment', value: 2 },
      { label: 'Hambatan moderate, ada bridging mechanism mulai terbentuk', value: 3 },
      { label: 'Minor hambatan, mostly execution dan scaling', value: 4 },
      { label: 'Minimal hambatan, sudah punya proven collaboration model', value: 5 },
    ],
  },
  {
    id: 'byan_masalah_2',
    dimension: 'masalah',
    persona: 'byanmara',
    text: 'Seberapa aware healthcare/medical tourism stakeholders terhadap regenerative tourism value?',
    options: [
      { label: 'Sangat rendah, bukan priority sama sekali', value: 1 },
      { label: 'Minimal awareness, sustainability peripheral', value: 2 },
      { label: 'Moderate awareness, mulai consider dalam strategy', value: 3 },
      { label: 'Strong awareness, actively integrate dalam offering', value: 4 },
      { label: 'Excellent alignment, regenerative tourism core differentiator', value: 5 },
    ],
  },
  {
    id: 'byan_rough_idea_1',
    dimension: 'rough_idea',
    persona: 'byanmara',
    text: 'Apakah ada vision/roadmap untuk positioning regenerative health tourism sebagai offering?',
    options: [
      { label: 'Belum ada, masih research phase', value: 1 },
      { label: 'Ada rough concept, belum detailed strategy', value: 2 },
      { label: 'Ada planning dasar dengan some pilot idea', value: 3 },
      { label: 'Ada structured strategy, mulai implementation', value: 4 },
      { label: 'Comprehensive roadmap dengan active execution & market positioning', value: 5 },
    ],
  },
  {
    id: 'byan_rough_idea_2',
    dimension: 'rough_idea',
    persona: 'byanmara',
    text: 'Seberapa urgent kebutuhan untuk connect dengan health tourism players & GHTA?',
    options: [
      { label: 'Tidak urgent, exploratory research phase', value: 1 },
      { label: 'Low priority, bisa nanti', value: 2 },
      { label: 'Moderate, perlu partnership development 6-12 bulan', value: 3 },
      { label: 'High priority, butuh intensive collaboration 3-6 bulan', value: 4 },
      { label: 'Very urgent, ready untuk strategic partnership sekarang', value: 5 },
    ],
  },
];

export const personas: Record<PersonaType, PersonaProfile> = {
  pimpinan_daerah: {
    label: 'Pimpinan Daerah',
    description: 'Gubernur, Bupati, atau Walikota',
    icon: 'government',
    questions: pimpinanDaerahQuestions,
  },
  dinas: {
    label: 'Dinas Kesehatan / Pariwisata',
    description: 'Kepala Dinas atau Koordinator Program',
    icon: 'department',
    questions: dinasQuestions,
  },
  rs_owner: {
    label: 'Pemilik / Direktur Utama RS',
    description: 'Owner atau Top Executive RS',
    icon: 'hospital',
    questions: rsOwnerQuestions,
  },
  rs_management: {
    label: 'Manajemen RS (Operasional)',
    description: 'Direktur Operasional, Direktur Pelayanan, atau Manager',
    icon: 'management',
    questions: rsManagementQuestions,
  },
  rs_marketing: {
    label: 'Marketing / Business Development RS',
    description: 'Kepala Marketing, Business Dev Manager, atau Sales',
    icon: 'marketing',
    questions: rsMarketingQuestions,
  },
  doctor: {
    label: 'Dokter Spesialis',
    description: 'Spesialis dengan potensi international patient',
    icon: 'doctor',
    questions: doctorQuestions,
  },
  hotel_manager: {
    label: 'Hotel Manager',
    description: 'Manajer hotel dengan opportunity untuk medical tourism positioning',
    icon: 'hotel',
    questions: hotelManagerQuestions,
  },
  spa_manager: {
    label: 'Spa Manager',
    description: 'Pengelola spa atau wellness center standalone',
    icon: 'spa',
    questions: spaManagerQuestions,
  },
  resort_manager: {
    label: 'Resort Manager',
    description: 'Manajer resort dengan integrated health-wellness potential',
    icon: 'resort',
    questions: resortManagerQuestions,
  },
  travel_agent: {
    label: 'Travel Agent',
    description: 'Agen perjalanan dengan capability untuk medical tourism packages',
    icon: 'travel',
    questions: travelAgentQuestions,
  },
  youth_leader: {
    label: 'Youth Leader (Pemuda Daerah)',
    description: 'Leader community pemuda dengan entrepreneurship & ambassador potential',
    icon: 'youth',
    questions: youthLeaderQuestions,
  },
  karang_taruna_leader: {
    label: 'Karang Taruna Leader',
    description: 'Ketua organisasi Karang Taruna dengan community mobilization capacity',
    icon: 'community',
    questions: karangTarunaLeaderQuestions,
  },
  village_head: {
    label: 'Kepala Desa',
    description: 'Village head dengan mandate untuk community development & tourism',
    icon: 'village',
    questions: villageHeadQuestions,
  },
  tourism_manager: {
    label: 'Tourism Manager',
    description: 'Pengelola desa wisata atau destination management organization',
    icon: 'tourism',
    questions: tourismManagerQuestions,
  },
  national_park_manager: {
    label: 'National Park Manager',
    description: 'Pengelola taman nasional atau protected area dengan wellness integration',
    icon: 'nature',
    questions: nationalParkManagerQuestions,
  },
  byanmara: {
    label: 'Byanmara (ESG/Regenerative Tourism)',
    description: 'Professional di regenerative tourism, blue carbon, & community-based development',
    icon: 'sustainability',
    questions: byanmaraQuestions,
  },
};
